  CREATE TABLE training_journals (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      course_id bigint NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
      company_id bigint REFERENCES companies(id) ON DELETE RESTRICT,
      title text NOT NULL,
      course_symbol text NOT NULL,
      organizer_name text NOT NULL,
      organizer_address text,
      location text NOT NULL,
      form_of_training text NOT NULL,
      legal_basis text NOT NULL,
      date_start date NOT NULL,
      date_end date NOT NULL,
      total_hours numeric(6,2) NOT NULL DEFAULT 0,
      notes text,
      status text NOT NULL DEFAULT 'draft',
      created_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      closed_at timestamptz,
      CONSTRAINT training_journals_status_check
          CHECK (status IN ('draft', 'closed')),
      CONSTRAINT training_journals_dates_check
          CHECK (date_end >= date_start),
      CONSTRAINT training_journals_total_hours_check
          CHECK (total_hours >= 0)
  );

  CREATE TABLE training_journal_attendees (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      student_id bigint NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
      full_name_snapshot text NOT NULL,
      birthdate_snapshot date,
      company_name_snapshot text,
      sort_order integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendees_sort_order_check
          CHECK (sort_order >= 0),
      CONSTRAINT training_journal_attendees_journal_student_unique
          UNIQUE (journal_id, student_id)
  );

  CREATE TABLE training_journal_sessions (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      session_date date NOT NULL,
      start_time time,
      end_time time,
      hours numeric(6,2) NOT NULL,
      topic text NOT NULL,
      trainer_name text NOT NULL,
      sort_order integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_sessions_hours_check
          CHECK (hours > 0),
      CONSTRAINT training_journal_sessions_sort_order_check
          CHECK (sort_order >= 0),
      CONSTRAINT training_journal_sessions_time_check
          CHECK (
              start_time IS NULL
              OR end_time IS NULL
              OR end_time >= start_time
          )
  );

  CREATE INDEX training_journals_course_id_idx
      ON training_journals (course_id);

  CREATE INDEX training_journals_company_id_idx
      ON training_journals (company_id);

  CREATE INDEX training_journals_status_date_start_idx
      ON training_journals (status, date_start DESC);

  CREATE INDEX training_journal_attendees_journal_id_sort_order_idx
      ON training_journal_attendees (journal_id, sort_order, id);

  CREATE INDEX training_journal_sessions_journal_id_session_date_sort_order_idx
      ON training_journal_sessions (journal_id, session_date, sort_order, id);
