CREATE TABLE training_journal_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_session_id bigint NOT NULL REFERENCES training_journal_sessions(id) ON DELETE CASCADE,
    journal_attendee_id bigint NOT NULL REFERENCES training_journal_attendees(id) ON DELETE CASCADE,
    present boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT training_journal_attendance_session_attendee_unique
        UNIQUE (journal_session_id, journal_attendee_id)
);

CREATE INDEX training_journal_attendance_session_id_idx
    ON training_journal_attendance (journal_session_id);

CREATE INDEX training_journal_attendance_attendee_id_idx
    ON training_journal_attendance (journal_attendee_id);
