CREATE TABLE training_journal_attendance_scans (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      file_name text NOT NULL,
      content_type text NOT NULL,
      file_size bigint NOT NULL,
      file_data bytea NOT NULL,
      uploaded_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendance_scans_file_size_check CHECK (file_size > 0),
      CONSTRAINT training_journal_attendance_scans_journal_unique UNIQUE (journal_id)
  );

CREATE INDEX training_journal_attendance_scans_uploaded_by_idx
      ON training_journal_attendance_scans (uploaded_by_user_id);
