CREATE TABLE course_certificate_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    language_code text NOT NULL,
    course_name text NOT NULL,
    course_program json NOT NULL,
    cert_front_page text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT course_certificate_translations_language_code_check
        CHECK (
            language_code = lower(btrim(language_code))
            AND language_code <> ''
            AND language_code <> 'pl'
        ),
    CONSTRAINT course_certificate_translations_course_language_unique
        UNIQUE (course_id, language_code)
);
CREATE INDEX course_certificate_translations_course_id_idx
    ON course_certificate_translations (course_id);
ALTER TABLE certificates
    ADD COLUMN language_code text NOT NULL DEFAULT 'pl',
    ADD COLUMN student_firstname_snapshot text,
    ADD COLUMN student_secondname_snapshot text,
    ADD COLUMN student_lastname_snapshot text,
    ADD COLUMN student_birthdate_snapshot date,
    ADD COLUMN student_birthplace_snapshot text,
    ADD COLUMN student_pesel_snapshot text,
    ADD COLUMN company_name_snapshot text,
    ADD COLUMN course_name_snapshot text,
    ADD COLUMN course_symbol_snapshot text,
    ADD COLUMN course_expiry_time_snapshot text,
    ADD COLUMN course_program_snapshot json,
    ADD COLUMN cert_front_page_snapshot text;
WITH snapshot_source AS (
    SELECT
        c.id,
        s.firstname AS student_firstname_snapshot,
        s.secondname AS student_secondname_snapshot,
        s.lastname AS student_lastname_snapshot,
        s.birthdate AS student_birthdate_snapshot,
        s.birthplace AS student_birthplace_snapshot,
        s.pesel AS student_pesel_snapshot,
        comp.name AS company_name_snapshot,
        cr.name AS course_name_snapshot,
        cr.symbol AS course_symbol_snapshot,
        cr.expirytime AS course_expiry_time_snapshot,
        COALESCE(cr.courseprogram, '[]'::json) AS course_program_snapshot,
        COALESCE(cr.certfrontpage, '') AS cert_front_page_snapshot
    FROM certificates c
    JOIN students s ON s.id = c.student_id
    LEFT JOIN companies comp ON comp.id = s.company_id
    JOIN registries r ON r.id = c.registry_id
    JOIN courses cr ON cr.id = r.course_id
)
UPDATE certificates c
SET
    student_firstname_snapshot = src.student_firstname_snapshot,
    student_secondname_snapshot = src.student_secondname_snapshot,
    student_lastname_snapshot = src.student_lastname_snapshot,
    student_birthdate_snapshot = src.student_birthdate_snapshot,
    student_birthplace_snapshot = src.student_birthplace_snapshot,
    student_pesel_snapshot = src.student_pesel_snapshot,
    company_name_snapshot = src.company_name_snapshot,
    course_name_snapshot = src.course_name_snapshot,
    course_symbol_snapshot = src.course_symbol_snapshot,
    course_expiry_time_snapshot = src.course_expiry_time_snapshot,
    course_program_snapshot = src.course_program_snapshot,
    cert_front_page_snapshot = src.cert_front_page_snapshot
FROM snapshot_source src
WHERE src.id = c.id;
ALTER TABLE certificates
    ALTER COLUMN student_firstname_snapshot SET NOT NULL,
    ALTER COLUMN student_lastname_snapshot SET NOT NULL,
    ALTER COLUMN student_birthdate_snapshot SET NOT NULL,
    ALTER COLUMN student_birthplace_snapshot SET NOT NULL,
    ALTER COLUMN course_name_snapshot SET NOT NULL,
    ALTER COLUMN course_symbol_snapshot SET NOT NULL,
    ALTER COLUMN course_program_snapshot SET NOT NULL,
    ALTER COLUMN cert_front_page_snapshot SET NOT NULL;
ALTER TABLE certificates
    ADD CONSTRAINT certificates_language_code_check
        CHECK (
            language_code = lower(btrim(language_code))
            AND language_code <> ''
        );
