CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL,
    entity_id bigint NOT NULL,
    action text NOT NULL,
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    actor_user_email_snapshot text,
    actor_user_name_snapshot text,
    request_id text,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_entity_created_idx
    ON audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_log_actor_created_idx
    ON audit_log (actor_user_id, created_at DESC);
CREATE INDEX audit_log_created_idx
    ON audit_log (created_at DESC);
