-- Klucze API dla integracji serwer-serwer.
--
-- Klucz jest zawsze powiązany z wierszem w users (kontem serwisowym), dzięki
-- czemu RequireAdmin, audit log i pozostałe kontrole uprawnień działają tak
-- samo jak dla logowania sesyjnego.
--
-- token_hash trzyma sha256 surowego klucza - identycznie jak api_sessions.token.
-- Surowy klucz jest pokazywany wyłącznie raz, w odpowiedzi na jego utworzenie.
--
-- scopes zawężają to, co kluczem można zrobić, niezależnie od roli konta
-- serwisowego. Pusta tablica oznacza klucz bez żadnych uprawnień (celowo -
-- brak zakresów nie może oznaczać pełnego dostępu).
CREATE TABLE api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    prefix text NOT NULL,
    token_hash text NOT NULL UNIQUE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scopes text[] NOT NULL DEFAULT '{}',
    expires_at timestamptz,
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT api_keys_name_not_blank CHECK (btrim(name) <> '')
);

CREATE INDEX api_keys_user_id_idx ON api_keys (user_id);

-- Lista kluczy w panelu admina pokazuje najpierw aktywne, najnowsze.
CREATE INDEX api_keys_active_created_idx
    ON api_keys (created_at DESC)
    WHERE revoked_at IS NULL;
