-- Webhook wychodzący: odbiorcy, kolejka zdarzeń i stan doręczeń.
--
--   - webhook_endpoints   - odbiorcy (adres + wspólny sekret HMAC). Konfigurowani poza API,
--                           bezpośrednio w bazie (patrz INTEGRATION.md, sekcja o webhookach).
--   - webhook_events      - zdarzenia zapisywane w TEJ SAMEJ transakcji co zmiana, której dotyczą.
--                           payload to dokładne bajty wysyłanego ciała (podpisywane przy wysyłce),
--                           occurred_at rośnie ściśle w obrębie subject_key (np. certificate:123).
--   - webhook_deliveries  - doręczenie zdarzenia do odbiorcy: stan, liczba prób, termin
--                           kolejnej próby, ostatni kod odpowiedzi/błąd.
--   - certificates.idempotency_key - trwały identyfikator platformy przy zaświadczeniu
--                           (tabela idempotency_keys jest czyszczona po 30 dniach, a zdarzenia
--                           o unieważnieniu mogą przyjść później). Duplikat dziedziczy klucz oryginału.
--
-- Wpływ na istniejące dane:
--   - certificates.idempotency_key dostaje wartość dla zaświadczeń, które mają wpis
--     w idempotency_keys (wystawionych z nagłówkiem Idempotency-Key); pozostałe mają NULL,
--   - nowe tabele są puste - migracja nie tworzy zdarzeń dla istniejących dokumentów
--     i nie konfiguruje żadnego odbiorcy.
-- Uruchamiać przez: psql --single-transaction -v ON_ERROR_STOP=1 -f

ALTER TABLE certificates ADD COLUMN idempotency_key text;

UPDATE certificates c
SET idempotency_key = ik.key
FROM idempotency_keys ik
WHERE ik.certificate_id = c.id;

CREATE TABLE webhook_endpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text NOT NULL,
    secret text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_endpoints_url_http CHECK (url ~ '^https?://'),
    CONSTRAINT webhook_endpoints_secret_not_blank CHECK (btrim(secret) <> '')
);

CREATE TABLE webhook_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    subject_key text NOT NULL,
    occurred_at timestamptz NOT NULL,
    payload bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX webhook_events_subject_idx ON webhook_events (subject_key, occurred_at DESC);

CREATE TABLE webhook_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES webhook_events(id) ON DELETE CASCADE,
    endpoint_id bigint NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
    subject_key text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    locked_until timestamptz,
    last_status_code integer,
    last_error text,
    delivered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_deliveries_status_check CHECK (status IN ('pending', 'delivered', 'failed')),
    CONSTRAINT webhook_deliveries_event_endpoint_unique UNIQUE (event_id, endpoint_id)
);

-- Wybór kolejnych doręczeń do wysłania.
CREATE INDEX webhook_deliveries_pending_idx
    ON webhook_deliveries (next_attempt_at, id)
    WHERE status = 'pending';

-- Kolejność per odbiorca i przedmiot: starsze oczekujące doręczenie blokuje nowsze.
CREATE INDEX webhook_deliveries_subject_pending_idx
    ON webhook_deliveries (endpoint_id, subject_key, id)
    WHERE status = 'pending';
