-- Nadruki na zaświadczeniach wystawianych przez platformę: dwie pieczątki i podpis.
--
-- Taki dokument trafia do kursanta elektronicznie i nikt nie przystawia na nim pieczątki
-- ręcznie, w odróżnieniu od wydruków z aplikacji webowej. Pliki wgrywa administrator
-- i obowiązują dla całego rejestru - system obsługuje jeden podmiot, a pieczątka i podpis
-- należą do organizatora szkolenia, nie do pojedynczego kursu. Stąd jeden wiersz na rodzaj
-- (UNIQUE kind), a nie powiązanie z kursem czy firmą.
--
-- Tło giloszowe NIE jest tu przechowywane - powstaje proceduralnie w api/internal/guilloche.
--
-- Nazwy rodzajów są celowo identyczne ze znacznikami szablonu ({{ pieczatka_1 }} itd.),
-- żeby nie trzeba było utrzymywać tabelki mapującej jedno na drugie.
--
-- Wpływ na istniejące dane: brak, tabela startuje pusta. Dopóki nic nie zostanie wgrane,
-- wydruki wyglądają dokładnie tak jak dotąd.
-- Uruchamiać przez: psql --single-transaction -v ON_ERROR_STOP=1 -f

CREATE TABLE certificate_print_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind text NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    file_size bigint NOT NULL,
    file_data bytea NOT NULL,
    print_width_mm smallint NOT NULL DEFAULT 35,
    uploaded_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT certificate_print_assets_kind_check
        CHECK (kind IN ('pieczatka_1', 'pieczatka_2', 'podpis')),
    CONSTRAINT certificate_print_assets_kind_unique UNIQUE (kind),
    CONSTRAINT certificate_print_assets_file_size_check CHECK (file_size > 0),
    -- API przekodowuje każde wejście do PNG (internal/certassets), a baza to utrwala.
    -- To także bariera bezpieczeństwa: typ MIME trafia na wydruk w atrybucie src obrazu,
    -- a HTML nadruku omija escapowanie (rawValues w internal/certificates/pdf.go).
    CONSTRAINT certificate_print_assets_content_type_check
        CHECK (content_type = 'image/png'),
    -- Szerokość nadruku ustala administrator, bo proporcje skanów są nieprzewidywalne.
    -- Wysokość liczy się sama. Górne ograniczenie wynika z szerokości paska awaryjnego
    -- u dołu strony, który musi zmieścić dwie pieczątki, podpis i ominąć kod QR.
    CONSTRAINT certificate_print_assets_width_check
        CHECK (print_width_mm BETWEEN 10 AND 60)
);

CREATE INDEX certificate_print_assets_uploaded_by_idx
    ON certificate_print_assets (uploaded_by_user_id);
