-- Biblioteka podstaw prawnych cytowanych na zaświadczeniach.
--
-- Dotąd podstawa prawna była wpisana na sztywno w szablon każdego kursu (131 ze 132
-- szablonów), więc zmiana przepisu oznaczała ręczną poprawkę każdego z nich - i takie
-- poprawki zostawiły już literówki ("Dz. U. z 20179", "6 października 2024 r." zamiast 2023).
-- Teraz kurs wskazuje jedną podstawę z biblioteki, a szablon wstawia ją znacznikiem
-- {{ podstawa_prawna }}.
--
--   - legal_bases                       - biblioteka; treść zaczyna się od "§ ..."
--                                         ("na podstawie" zostaje w szablonie),
--   - courses.legal_basis_id            - podstawa kursu; może być pusta,
--   - certificates.legal_basis_snapshot - treść zamrożona przy wystawieniu.
--
-- Migawka z tego samego powodu co migawka szablonu: zaświadczenie wydane pod
-- rozporządzeniem z 2019 r. ma je cytować także po zmianie przepisów. Poprawka
-- w bibliotece dotyczy wyłącznie dokumentów wystawionych później.
--
-- ON DELETE RESTRICT: podstawy, którą wskazuje kurs, nie da się usunąć - API odpowiada
-- wtedy 409, a nie zostawia kursu z cichym brakiem podstawy na wydruku.
--
-- Wpływ na istniejące dane: brak. Kursy dostają NULL, zaświadczenia NULL - ich zamrożone
-- szablony mają tekst wpisany na sztywno. Przeniesienie tekstu z szablonów do biblioteki
-- robi osobna migracja 0030, uruchamiana PO wdrożeniu kodu, który zna znacznik.
-- Uruchamiać przez: psql --single-transaction -v ON_ERROR_STOP=1 -f

CREATE TABLE legal_bases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT legal_bases_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT legal_bases_content_not_blank CHECK (btrim(content) <> '')
);

-- Nazwa służy do wyboru z listy, więc nie może się powtarzać, także różnicą wielkości liter.
CREATE UNIQUE INDEX legal_bases_name_uidx ON legal_bases (lower(btrim(name)));

CREATE FUNCTION legal_bases_touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF (to_jsonb(NEW) - 'updated_at') IS DISTINCT FROM (to_jsonb(OLD) - 'updated_at') THEN
        NEW.updated_at := clock_timestamp();
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER legal_bases_touch_updated_at
    BEFORE UPDATE ON legal_bases
    FOR EACH ROW
    EXECUTE FUNCTION legal_bases_touch_updated_at();

ALTER TABLE courses
    ADD COLUMN legal_basis_id bigint REFERENCES legal_bases(id) ON DELETE RESTRICT;

CREATE INDEX courses_legal_basis_id_idx ON courses (legal_basis_id) WHERE legal_basis_id IS NOT NULL;

ALTER TABLE certificates
    ADD COLUMN legal_basis_snapshot text;
