--
-- PostgreSQL database dump
--


-- Dumped from database version 15.18 (Homebrew)
-- Dumped by pg_dump version 15.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id bigint NOT NULL,
    name text NOT NULL,
    prefix text NOT NULL,
    token_hash text NOT NULL,
    user_id bigint NOT NULL,
    scopes text[] DEFAULT '{}'::text[] NOT NULL,
    expires_at timestamp with time zone,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT api_keys_name_not_blank CHECK ((btrim(name) <> ''::text))
);


--
-- Name: api_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_sessions (
    token text NOT NULL,
    user_id bigint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    entity_type text NOT NULL,
    entity_id bigint NOT NULL,
    action text NOT NULL,
    actor_user_id bigint,
    actor_user_email_snapshot text,
    actor_user_name_snapshot text,
    request_id text,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.certificates (
    id bigint NOT NULL,
    date date NOT NULL,
    student_id integer NOT NULL,
    coursedatestart date NOT NULL,
    coursedateend date,
    registry_id bigint NOT NULL,
    deleted_at timestamp with time zone,
    deleted_by_user_id bigint,
    delete_reason text,
    language_code text DEFAULT 'pl'::text NOT NULL,
    student_firstname_snapshot text NOT NULL,
    student_secondname_snapshot text,
    student_lastname_snapshot text NOT NULL,
    student_birthdate_snapshot date NOT NULL,
    student_birthplace_snapshot text NOT NULL,
    student_pesel_snapshot text,
    company_name_snapshot text,
    course_name_snapshot text NOT NULL,
    course_symbol_snapshot text NOT NULL,
    course_expiry_time_snapshot text,
    course_program_snapshot json NOT NULL,
    cert_front_page_snapshot text NOT NULL,
    company_id_snapshot bigint,
    CONSTRAINT certificates_language_code_check CHECK (((language_code = lower(btrim(language_code))) AND (language_code <> ''::text)))
);


--
-- Name: certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.certificates_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: certificates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.certificates_id_seq OWNED BY public.certificates.id;


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    name text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    zipcode text NOT NULL,
    nip text NOT NULL,
    email text,
    contactperson text,
    telephoneno text NOT NULL,
    note text,
    expiry_notifications_enabled boolean DEFAULT false NOT NULL,
    expiry_notification_email text
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.companies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: companies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.companies_id_seq OWNED BY public.companies.id;


--
-- Name: course_certificate_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_certificate_translations (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    language_code text NOT NULL,
    course_name text NOT NULL,
    course_program json NOT NULL,
    cert_front_page text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT course_certificate_translations_language_code_check CHECK (((language_code = lower(btrim(language_code))) AND (language_code <> ''::text) AND (language_code <> 'pl'::text)))
);


--
-- Name: course_certificate_translations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_certificate_translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_certificate_translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oldcourses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oldcourses (
    id bigint NOT NULL,
    name text NOT NULL,
    symbol text NOT NULL,
    expirytime text,
    courseprogram json,
    certfrontpage text
);


--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.courses_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: courses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.courses_id_seq OWNED BY public.oldcourses.id;


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id bigint DEFAULT nextval('public.courses_id_seq'::regclass) NOT NULL,
    mainname text,
    name text NOT NULL,
    symbol text NOT NULL,
    expirytime text,
    courseprogram json,
    certfrontpage text
);


--
-- Name: registries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registries (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    year bigint NOT NULL,
    number integer NOT NULL
);


--
-- Name: registry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.registry_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: registry_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.registry_id_seq OWNED BY public.registries.id;


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    secondname text,
    birthdate date NOT NULL,
    birthplace text NOT NULL,
    pesel text,
    addressstreet text,
    addresscity text,
    telephoneno text,
    company_id bigint,
    addresszip text
);


--
-- Name: students_sampleid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.students_sampleid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: students_sampleid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.students_sampleid_seq OWNED BY public.students.id;


--
-- Name: training_journal_attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_journal_attendance (
    id bigint NOT NULL,
    journal_session_id bigint NOT NULL,
    journal_attendee_id bigint NOT NULL,
    present boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: training_journal_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_journal_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_journal_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_journal_attendance_scans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_journal_attendance_scans (
    id bigint NOT NULL,
    journal_id bigint NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    file_size bigint NOT NULL,
    file_data bytea NOT NULL,
    uploaded_by_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT training_journal_attendance_scans_file_size_check CHECK ((file_size > 0))
);


--
-- Name: training_journal_attendance_scans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_journal_attendance_scans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_journal_attendance_scans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_journal_attendees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_journal_attendees (
    id bigint NOT NULL,
    journal_id bigint NOT NULL,
    student_id bigint NOT NULL,
    full_name_snapshot text NOT NULL,
    birthdate_snapshot date,
    company_name_snapshot text,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    certificate_id bigint,
    CONSTRAINT training_journal_attendees_sort_order_check CHECK ((sort_order >= 0))
);


--
-- Name: training_journal_attendees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_journal_attendees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_journal_attendees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_journal_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_journal_sessions (
    id bigint NOT NULL,
    journal_id bigint NOT NULL,
    session_date date NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    hours numeric(6,2) NOT NULL,
    topic text NOT NULL,
    trainer_name text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT training_journal_sessions_hours_check CHECK ((hours > (0)::numeric)),
    CONSTRAINT training_journal_sessions_sort_order_check CHECK ((sort_order >= 0)),
    CONSTRAINT training_journal_sessions_time_check CHECK (((start_time IS NULL) OR (end_time IS NULL) OR (end_time >= start_time)))
);


--
-- Name: training_journal_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_journal_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_journal_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_journal_signed_scans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_journal_signed_scans (
    id bigint NOT NULL,
    journal_id bigint NOT NULL,
    file_name text NOT NULL,
    content_type text NOT NULL,
    file_size bigint NOT NULL,
    file_data bytea NOT NULL,
    uploaded_by_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT training_journal_signed_scans_file_size_check CHECK ((file_size > 0))
);


--
-- Name: training_journal_signed_scans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_journal_signed_scans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_journal_signed_scans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_journals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_journals (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    company_id bigint,
    title text NOT NULL,
    course_symbol text NOT NULL,
    organizer_name text NOT NULL,
    organizer_address text,
    location text NOT NULL,
    form_of_training text NOT NULL,
    legal_basis text NOT NULL,
    date_start date NOT NULL,
    date_end date NOT NULL,
    total_hours numeric(6,2) DEFAULT 0 NOT NULL,
    notes text,
    status text DEFAULT 'draft'::text NOT NULL,
    created_by_user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone,
    CONSTRAINT training_journals_dates_check CHECK ((date_end >= date_start)),
    CONSTRAINT training_journals_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'closed'::text]))),
    CONSTRAINT training_journals_total_hours_check CHECK ((total_hours >= (0)::numeric))
);


--
-- Name: training_journals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_journals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_journals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email text NOT NULL,
    password bytea NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    role integer NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: certificates id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates ALTER COLUMN id SET DEFAULT nextval('public.certificates_id_seq'::regclass);


--
-- Name: companies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies ALTER COLUMN id SET DEFAULT nextval('public.companies_id_seq'::regclass);


--
-- Name: oldcourses id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oldcourses ALTER COLUMN id SET DEFAULT nextval('public.courses_id_seq'::regclass);


--
-- Name: registries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registries ALTER COLUMN id SET DEFAULT nextval('public.registry_id_seq'::regclass);


--
-- Name: students id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students ALTER COLUMN id SET DEFAULT nextval('public.students_sampleid_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_token_hash_key UNIQUE (token_hash);


--
-- Name: api_sessions api_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_sessions
    ADD CONSTRAINT api_sessions_pkey PRIMARY KEY (token);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: certificates certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);


--
-- Name: companies check_unique_nip; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT check_unique_nip UNIQUE (nip);


--
-- Name: courses check_unique_symbol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT check_unique_symbol UNIQUE (symbol);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: course_certificate_translations course_certificate_translations_course_language_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_certificate_translations
    ADD CONSTRAINT course_certificate_translations_course_language_unique UNIQUE (course_id, language_code);


--
-- Name: course_certificate_translations course_certificate_translations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_certificate_translations
    ADD CONSTRAINT course_certificate_translations_pkey PRIMARY KEY (id);


--
-- Name: oldcourses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oldcourses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey1 PRIMARY KEY (id);


--
-- Name: registries registries_course_year_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registries
    ADD CONSTRAINT registries_course_year_number_key UNIQUE (course_id, year, number);


--
-- Name: registries registry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registries
    ADD CONSTRAINT registry_pkey PRIMARY KEY (id);


--
-- Name: students students_person_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_person_unique UNIQUE (firstname, lastname, birthdate);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: training_journal_attendance training_journal_attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance
    ADD CONSTRAINT training_journal_attendance_pkey PRIMARY KEY (id);


--
-- Name: training_journal_attendance_scans training_journal_attendance_scans_journal_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance_scans
    ADD CONSTRAINT training_journal_attendance_scans_journal_unique UNIQUE (journal_id);


--
-- Name: training_journal_attendance_scans training_journal_attendance_scans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance_scans
    ADD CONSTRAINT training_journal_attendance_scans_pkey PRIMARY KEY (id);


--
-- Name: training_journal_attendance training_journal_attendance_session_attendee_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance
    ADD CONSTRAINT training_journal_attendance_session_attendee_unique UNIQUE (journal_session_id, journal_attendee_id);


--
-- Name: training_journal_attendees training_journal_attendees_journal_student_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendees
    ADD CONSTRAINT training_journal_attendees_journal_student_unique UNIQUE (journal_id, student_id);


--
-- Name: training_journal_attendees training_journal_attendees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendees
    ADD CONSTRAINT training_journal_attendees_pkey PRIMARY KEY (id);


--
-- Name: training_journal_sessions training_journal_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_sessions
    ADD CONSTRAINT training_journal_sessions_pkey PRIMARY KEY (id);


--
-- Name: training_journal_signed_scans training_journal_signed_scans_journal_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_signed_scans
    ADD CONSTRAINT training_journal_signed_scans_journal_unique UNIQUE (journal_id);


--
-- Name: training_journal_signed_scans training_journal_signed_scans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_signed_scans
    ADD CONSTRAINT training_journal_signed_scans_pkey PRIMARY KEY (id);


--
-- Name: training_journals training_journals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journals
    ADD CONSTRAINT training_journals_pkey PRIMARY KEY (id);


--
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: api_keys_active_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_keys_active_created_idx ON public.api_keys USING btree (created_at DESC) WHERE (revoked_at IS NULL);


--
-- Name: api_keys_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_keys_user_id_idx ON public.api_keys USING btree (user_id);


--
-- Name: audit_log_actor_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_actor_created_idx ON public.audit_log USING btree (actor_user_id, created_at DESC);


--
-- Name: audit_log_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_created_idx ON public.audit_log USING btree (created_at DESC);


--
-- Name: audit_log_entity_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_entity_created_idx ON public.audit_log USING btree (entity_type, entity_id, created_at DESC);


--
-- Name: certificates_company_id_snapshot_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX certificates_company_id_snapshot_idx ON public.certificates USING btree (company_id_snapshot) WHERE (company_id_snapshot IS NOT NULL);


--
-- Name: certificates_deleted_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX certificates_deleted_at_idx ON public.certificates USING btree (deleted_at);


--
-- Name: course_certificate_translations_course_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_certificate_translations_course_id_idx ON public.course_certificate_translations USING btree (course_id);


--
-- Name: idx_api_sessions_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_sessions_expires_at ON public.api_sessions USING btree (expires_at);


--
-- Name: students_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX students_company_id_idx ON public.students USING btree (company_id) WHERE (company_id IS NOT NULL);


--
-- Name: students_person_normalized_uidx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX students_person_normalized_uidx ON public.students USING btree (lower(btrim(firstname)), lower(btrim(lastname)), birthdate);


--
-- Name: training_journal_attendance_attendee_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journal_attendance_attendee_id_idx ON public.training_journal_attendance USING btree (journal_attendee_id);


--
-- Name: training_journal_attendance_scans_uploaded_by_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journal_attendance_scans_uploaded_by_idx ON public.training_journal_attendance_scans USING btree (uploaded_by_user_id);


--
-- Name: training_journal_attendance_session_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journal_attendance_session_id_idx ON public.training_journal_attendance USING btree (journal_session_id);


--
-- Name: training_journal_attendees_certificate_id_uidx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX training_journal_attendees_certificate_id_uidx ON public.training_journal_attendees USING btree (certificate_id) WHERE (certificate_id IS NOT NULL);


--
-- Name: training_journal_attendees_journal_id_sort_order_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journal_attendees_journal_id_sort_order_idx ON public.training_journal_attendees USING btree (journal_id, sort_order, id);


--
-- Name: training_journal_sessions_journal_id_session_date_sort_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journal_sessions_journal_id_session_date_sort_order_id ON public.training_journal_sessions USING btree (journal_id, session_date, sort_order, id);


--
-- Name: training_journal_signed_scans_uploaded_by_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journal_signed_scans_uploaded_by_idx ON public.training_journal_signed_scans USING btree (uploaded_by_user_id);


--
-- Name: training_journals_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journals_company_id_idx ON public.training_journals USING btree (company_id);


--
-- Name: training_journals_course_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journals_course_id_idx ON public.training_journals USING btree (course_id);


--
-- Name: training_journals_status_date_start_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX training_journals_status_date_start_idx ON public.training_journals USING btree (status, date_start DESC);


--
-- Name: api_keys api_keys_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: api_sessions api_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_sessions
    ADD CONSTRAINT api_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: audit_log audit_log_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: certificates certificates_Registry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT "certificates_Registry_id_fkey" FOREIGN KEY (registry_id) REFERENCES public.registries(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: certificates certificates_Student_Id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT "certificates_Student_Id_fkey" FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: certificates certificates_company_id_snapshot_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_company_id_snapshot_fkey FOREIGN KEY (company_id_snapshot) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- Name: certificates certificates_deleted_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_deleted_by_user_id_fkey FOREIGN KEY (deleted_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: course_certificate_translations course_certificate_translations_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_certificate_translations
    ADD CONSTRAINT course_certificate_translations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: registries registries_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registries
    ADD CONSTRAINT registries_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE RESTRICT;


--
-- Name: students students_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL;


--
-- Name: training_journal_attendance training_journal_attendance_journal_attendee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance
    ADD CONSTRAINT training_journal_attendance_journal_attendee_id_fkey FOREIGN KEY (journal_attendee_id) REFERENCES public.training_journal_attendees(id) ON DELETE CASCADE;


--
-- Name: training_journal_attendance training_journal_attendance_journal_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance
    ADD CONSTRAINT training_journal_attendance_journal_session_id_fkey FOREIGN KEY (journal_session_id) REFERENCES public.training_journal_sessions(id) ON DELETE CASCADE;


--
-- Name: training_journal_attendance_scans training_journal_attendance_scans_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance_scans
    ADD CONSTRAINT training_journal_attendance_scans_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.training_journals(id) ON DELETE CASCADE;


--
-- Name: training_journal_attendance_scans training_journal_attendance_scans_uploaded_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendance_scans
    ADD CONSTRAINT training_journal_attendance_scans_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: training_journal_attendees training_journal_attendees_certificate_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendees
    ADD CONSTRAINT training_journal_attendees_certificate_id_fkey FOREIGN KEY (certificate_id) REFERENCES public.certificates(id) ON DELETE SET NULL;


--
-- Name: training_journal_attendees training_journal_attendees_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendees
    ADD CONSTRAINT training_journal_attendees_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.training_journals(id) ON DELETE CASCADE;


--
-- Name: training_journal_attendees training_journal_attendees_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_attendees
    ADD CONSTRAINT training_journal_attendees_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id) ON DELETE RESTRICT;


--
-- Name: training_journal_sessions training_journal_sessions_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_sessions
    ADD CONSTRAINT training_journal_sessions_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.training_journals(id) ON DELETE CASCADE;


--
-- Name: training_journal_signed_scans training_journal_signed_scans_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_signed_scans
    ADD CONSTRAINT training_journal_signed_scans_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.training_journals(id) ON DELETE CASCADE;


--
-- Name: training_journal_signed_scans training_journal_signed_scans_uploaded_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journal_signed_scans
    ADD CONSTRAINT training_journal_signed_scans_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: training_journals training_journals_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journals
    ADD CONSTRAINT training_journals_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


--
-- Name: training_journals training_journals_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journals
    ADD CONSTRAINT training_journals_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE RESTRICT;


--
-- Name: training_journals training_journals_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_journals
    ADD CONSTRAINT training_journals_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--


