// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, prefix, token_hash, user_id, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, prefix, user_id, scopes, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	UserID     int64              `json:"user_id"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.UserID,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.UserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, prefix, user_id, scopes, expires_at, last_used_at, revoked_at, created_at
FROM api_keys
WHERE id = $1
`

type GetAPIKeyByIDRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	UserID     int64              `json:"user_id"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, id int64) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.UserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAPIKeyByTokenHash = `-- name: GetActiveAPIKeyByTokenHash :one
SELECT k.id,
       k.name,
       k.prefix,
       k.scopes,
       k.expires_at,
       k.last_used_at,
       u.id AS user_id,
       u.email,
       u.password,
       u.firstname,
       u.lastname,
       u.role
FROM api_keys k
JOIN users u ON u.id = k.user_id
WHERE k.token_hash = $1
  AND k.revoked_at IS NULL
  AND (k.expires_at IS NULL OR k.expires_at > now())
`

type GetActiveAPIKeyByTokenHashRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	UserID     int64              `json:"user_id"`
	Email      string             `json:"email"`
	Password   []byte             `json:"password"`
	Firstname  string             `json:"firstname"`
	Lastname   string             `json:"lastname"`
	Role       int32              `json:"role"`
}

// Zwraca klucz razem z kontem serwisowym, żeby uwierzytelnienie żądania
// kosztowało jedno zapytanie. Klucze odwołane i wygasłe są odfiltrowane tutaj,
// więc middleware nie musi ich rozróżniać.
func (q *Queries) GetActiveAPIKeyByTokenHash(ctx context.Context, tokenHash string) (GetActiveAPIKeyByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByTokenHash, tokenHash)
	var i GetActiveAPIKeyByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT k.id,
       k.name,
       k.prefix,
       k.user_id,
       k.scopes,
       k.expires_at,
       k.last_used_at,
       k.revoked_at,
       k.created_at,
       u.email AS user_email,
       u.firstname AS user_firstname,
       u.lastname AS user_lastname
FROM api_keys k
JOIN users u ON u.id = k.user_id
ORDER BY k.revoked_at IS NOT NULL, k.created_at DESC
`

type ListAPIKeysRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Prefix        string             `json:"prefix"`
	UserID        int64              `json:"user_id"`
	Scopes        []string           `json:"scopes"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserEmail     string             `json:"user_email"`
	UserFirstname string             `json:"user_firstname"`
	UserLastname  string             `json:"user_lastname"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.UserID,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserFirstname,
			&i.UserLastname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

// Znacznik ostatniego użycia jest odświeżany co najwyżej raz na 5 minut, żeby
// ruch z klucza nie generował zapisu przy każdym żądaniu.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
