// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (
    entity_type,
    entity_id,
    action,
    actor_user_id,
    actor_user_email_snapshot,
    actor_user_name_snapshot,
    request_id,
    before_data,
    after_data,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id
`

type CreateAuditLogParams struct {
	EntityType             string      `json:"entity_type"`
	EntityID               int64       `json:"entity_id"`
	Action                 string      `json:"action"`
	ActorUserID            pgtype.Int8 `json:"actor_user_id"`
	ActorUserEmailSnapshot pgtype.Text `json:"actor_user_email_snapshot"`
	ActorUserNameSnapshot  pgtype.Text `json:"actor_user_name_snapshot"`
	RequestID              pgtype.Text `json:"request_id"`
	BeforeData             []byte      `json:"before_data"`
	AfterData              []byte      `json:"after_data"`
	Metadata               []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorUserID,
		arg.ActorUserEmailSnapshot,
		arg.ActorUserNameSnapshot,
		arg.RequestID,
		arg.BeforeData,
		arg.AfterData,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT
    id,
    entity_type,
    entity_id,
    action,
    actor_user_id,
    actor_user_email_snapshot,
    actor_user_name_snapshot,
    request_id,
    before_data,
    after_data,
    metadata,
    created_at
FROM audit_log
WHERE entity_type = $1
  AND entity_id = $2
ORDER BY created_at DESC, id DESC
`

type ListAuditLogsByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorUserID,
			&i.ActorUserEmailSnapshot,
			&i.ActorUserNameSnapshot,
			&i.RequestID,
			&i.BeforeData,
			&i.AfterData,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
