// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCertificatesByCourseID = `-- name: CountCertificatesByCourseID :one
SELECT COUNT(*)
FROM certificates c
JOIN registries r ON r.id = c.registry_id
WHERE r.course_id = $1
  AND ($2::date IS NULL OR c.date >= $2::date)
  AND ($3::date IS NULL OR c.date <= $3::date)
  AND c.deleted_at IS NULL
`

type CountCertificatesByCourseIDParams struct {
	CourseID int64       `json:"course_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

func (q *Queries) CountCertificatesByCourseID(ctx context.Context, arg CountCertificatesByCourseIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificatesByCourseID, arg.CourseID, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
    date,
    student_id,
    coursedatestart,
    coursedateend,
    registry_id,
    language_code,
    student_firstname_snapshot,
    student_secondname_snapshot,
    student_lastname_snapshot,
    student_birthdate_snapshot,
    student_birthplace_snapshot,
    student_pesel_snapshot,
    company_name_snapshot,
    course_name_snapshot,
    course_symbol_snapshot,
    course_expiry_time_snapshot,
    course_program_snapshot,
    cert_front_page_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING id
`

type CreateCertificateParams struct {
	Date                      pgtype.Date `json:"date"`
	StudentID                 int32       `json:"student_id"`
	CourseDateStart           pgtype.Date `json:"course_date_start"`
	CourseDateEnd             pgtype.Date `json:"course_date_end"`
	RegistryID                int64       `json:"registry_id"`
	LanguageCode              string      `json:"language_code"`
	StudentFirstnameSnapshot  string      `json:"student_firstname_snapshot"`
	StudentSecondnameSnapshot pgtype.Text `json:"student_secondname_snapshot"`
	StudentLastnameSnapshot   string      `json:"student_lastname_snapshot"`
	StudentBirthdateSnapshot  pgtype.Date `json:"student_birthdate_snapshot"`
	StudentBirthplaceSnapshot string      `json:"student_birthplace_snapshot"`
	StudentPeselSnapshot      pgtype.Text `json:"student_pesel_snapshot"`
	CompanyNameSnapshot       pgtype.Text `json:"company_name_snapshot"`
	CourseNameSnapshot        string      `json:"course_name_snapshot"`
	CourseSymbolSnapshot      string      `json:"course_symbol_snapshot"`
	CourseExpiryTimeSnapshot  pgtype.Text `json:"course_expiry_time_snapshot"`
	CourseProgramSnapshot     []byte      `json:"course_program_snapshot"`
	CertFrontPageSnapshot     string      `json:"cert_front_page_snapshot"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.Date,
		arg.StudentID,
		arg.CourseDateStart,
		arg.CourseDateEnd,
		arg.RegistryID,
		arg.LanguageCode,
		arg.StudentFirstnameSnapshot,
		arg.StudentSecondnameSnapshot,
		arg.StudentLastnameSnapshot,
		arg.StudentBirthdateSnapshot,
		arg.StudentBirthplaceSnapshot,
		arg.StudentPeselSnapshot,
		arg.CompanyNameSnapshot,
		arg.CourseNameSnapshot,
		arg.CourseSymbolSnapshot,
		arg.CourseExpiryTimeSnapshot,
		arg.CourseProgramSnapshot,
		arg.CertFrontPageSnapshot,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT
    c.id,
    c.date,
    c.student_id,
    c.student_firstname_snapshot AS student_firstname,
    c.student_secondname_snapshot AS student_secondname,
    c.student_lastname_snapshot AS student_lastname,
    c.student_birthdate_snapshot AS student_birthdate,
    c.student_birthplace_snapshot AS student_birthplace,
    c.student_pesel_snapshot AS student_pesel,
    c.company_name_snapshot AS company_name,
    c.coursedatestart AS course_date_start,
    c.coursedateend AS course_date_end,
    r.id AS registry_id,
    r.year AS registry_year,
    r.number::bigint AS registry_number,
    r.course_id AS course_id,
    c.course_name_snapshot AS course_name,
    c.course_symbol_snapshot AS course_symbol,
    c.course_expiry_time_snapshot AS course_expiry_time,
    c.course_program_snapshot::text AS course_program,
    c.cert_front_page_snapshot AS cert_front_page,
    c.language_code,
    tja.id AS journal_attendee_id,
    tj.id AS journal_id,
    tj.title AS journal_title,
    tj.status AS journal_status,
    COALESCE(
        CASE
            WHEN c.coursedateend IS NOT NULL
                AND c.course_expiry_time_snapshot IS NOT NULL
                AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
            THEN TO_CHAR(c.coursedateend + c.course_expiry_time_snapshot::int * 365, 'YYYY-MM-DD')
            ELSE NULL::text
        END,
        ''
    ) AS expiry_date
FROM certificates c
LEFT JOIN training_journal_attendees tja ON tja.certificate_id = c.id
LEFT JOIN training_journals tj ON tj.id = tja.journal_id
JOIN registries r ON r.id = c.registry_id
WHERE c.id = $1
  AND c.deleted_at IS NULL
`

type GetCertificateByIDRow struct {
	ID                int64       `json:"id"`
	Date              pgtype.Date `json:"date"`
	StudentID         int32       `json:"student_id"`
	StudentFirstname  string      `json:"student_firstname"`
	StudentSecondname pgtype.Text `json:"student_secondname"`
	StudentLastname   string      `json:"student_lastname"`
	StudentBirthdate  pgtype.Date `json:"student_birthdate"`
	StudentBirthplace string      `json:"student_birthplace"`
	StudentPesel      pgtype.Text `json:"student_pesel"`
	CompanyName       pgtype.Text `json:"company_name"`
	CourseDateStart   pgtype.Date `json:"course_date_start"`
	CourseDateEnd     pgtype.Date `json:"course_date_end"`
	RegistryID        int64       `json:"registry_id"`
	RegistryYear      int64       `json:"registry_year"`
	RegistryNumber    int64       `json:"registry_number"`
	CourseID          int64       `json:"course_id"`
	CourseName        string      `json:"course_name"`
	CourseSymbol      string      `json:"course_symbol"`
	CourseExpiryTime  pgtype.Text `json:"course_expiry_time"`
	CourseProgram     string      `json:"course_program"`
	CertFrontPage     string      `json:"cert_front_page"`
	LanguageCode      string      `json:"language_code"`
	JournalAttendeeID pgtype.Int8 `json:"journal_attendee_id"`
	JournalID         pgtype.Int8 `json:"journal_id"`
	JournalTitle      pgtype.Text `json:"journal_title"`
	JournalStatus     pgtype.Text `json:"journal_status"`
	ExpiryDate        interface{} `json:"expiry_date"`
}

func (q *Queries) GetCertificateByID(ctx context.Context, id int64) (GetCertificateByIDRow, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i GetCertificateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StudentID,
		&i.StudentFirstname,
		&i.StudentSecondname,
		&i.StudentLastname,
		&i.StudentBirthdate,
		&i.StudentBirthplace,
		&i.StudentPesel,
		&i.CompanyName,
		&i.CourseDateStart,
		&i.CourseDateEnd,
		&i.RegistryID,
		&i.RegistryYear,
		&i.RegistryNumber,
		&i.CourseID,
		&i.CourseName,
		&i.CourseSymbol,
		&i.CourseExpiryTime,
		&i.CourseProgram,
		&i.CertFrontPage,
		&i.LanguageCode,
		&i.JournalAttendeeID,
		&i.JournalID,
		&i.JournalTitle,
		&i.JournalStatus,
		&i.ExpiryDate,
	)
	return i, err
}

const listCertificates = `-- name: ListCertificates :many
SELECT
    c.id,
    c.date,
    c.student_firstname_snapshot AS student_firstname,
    c.student_lastname_snapshot AS student_lastname,
    c.company_name_snapshot AS company_name,
    c.course_name_snapshot AS course_name,
    c.course_symbol_snapshot AS course_symbol,
    r.year AS registry_year,
    r.number::bigint AS registry_number,
    c.coursedatestart AS course_date_start,
    c.coursedateend AS course_date_end,
    c.language_code,
    COALESCE(
        CASE
            WHEN c.coursedateend IS NOT NULL
                AND c.course_expiry_time_snapshot IS NOT NULL
                AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
            THEN TO_CHAR(c.coursedateend + c.course_expiry_time_snapshot::int * 365, 'YYYY-MM-DD')
            ELSE NULL::text
        END,
        ''
    ) AS expiry_date
FROM certificates c
JOIN registries r ON r.id = c.registry_id
WHERE
    (
        $1::text IS NULL
        OR COALESCE(c.student_firstname_snapshot, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(c.student_lastname_snapshot, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(c.company_name_snapshot, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(c.course_name_snapshot, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(c.course_symbol_snapshot, '') ILIKE '%' || $1::text || '%'
        OR (
            r.number::bigint::text || '/' || c.course_symbol_snapshot || '/' || r.year::text
        ) ILIKE '%' || $1::text || '%'
    )
    AND c.deleted_at IS NULL
ORDER BY c.date DESC, c.id DESC
LIMIT $2
`

type ListCertificatesParams struct {
	Search     pgtype.Text `json:"search"`
	LimitCount int32       `json:"limit_count"`
}

type ListCertificatesRow struct {
	ID               int64       `json:"id"`
	Date             pgtype.Date `json:"date"`
	StudentFirstname string      `json:"student_firstname"`
	StudentLastname  string      `json:"student_lastname"`
	CompanyName      pgtype.Text `json:"company_name"`
	CourseName       string      `json:"course_name"`
	CourseSymbol     string      `json:"course_symbol"`
	RegistryYear     int64       `json:"registry_year"`
	RegistryNumber   int64       `json:"registry_number"`
	CourseDateStart  pgtype.Date `json:"course_date_start"`
	CourseDateEnd    pgtype.Date `json:"course_date_end"`
	LanguageCode     string      `json:"language_code"`
	ExpiryDate       interface{} `json:"expiry_date"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listCertificates, arg.Search, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesRow{}
	for rows.Next() {
		var i ListCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.StudentFirstname,
			&i.StudentLastname,
			&i.CompanyName,
			&i.CourseName,
			&i.CourseSymbol,
			&i.RegistryYear,
			&i.RegistryNumber,
			&i.CourseDateStart,
			&i.CourseDateEnd,
			&i.LanguageCode,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByCourseID = `-- name: ListCertificatesByCourseID :many
SELECT
    c.id,
    c.date,
    c.student_firstname_snapshot AS student_firstname,
    c.student_lastname_snapshot AS student_lastname,
    c.company_name_snapshot AS company_name,
    c.course_name_snapshot AS course_name,
    c.course_symbol_snapshot AS course_symbol,
    r.year AS registry_year,
    r.number::bigint AS registry_number,
    c.coursedatestart AS course_date_start,
    c.coursedateend AS course_date_end,
    c.language_code,
    COALESCE(
        CASE
            WHEN c.coursedateend IS NOT NULL
                AND c.course_expiry_time_snapshot IS NOT NULL
                AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
            THEN TO_CHAR(c.coursedateend + c.course_expiry_time_snapshot::int * 365, 'YYYY-MM-DD')
            ELSE NULL::text
        END,
        ''
    ) AS expiry_date
FROM certificates c
JOIN registries r ON r.id = c.registry_id
WHERE r.course_id = $1
  AND ($2::date IS NULL OR c.date >= $2::date)
  AND ($3::date IS NULL OR c.date <= $3::date)
  AND c.deleted_at IS NULL
ORDER BY c.date DESC, c.id DESC
LIMIT $5
OFFSET $4
`

type ListCertificatesByCourseIDParams struct {
	CourseID    int64       `json:"course_id"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListCertificatesByCourseIDRow struct {
	ID               int64       `json:"id"`
	Date             pgtype.Date `json:"date"`
	StudentFirstname string      `json:"student_firstname"`
	StudentLastname  string      `json:"student_lastname"`
	CompanyName      pgtype.Text `json:"company_name"`
	CourseName       string      `json:"course_name"`
	CourseSymbol     string      `json:"course_symbol"`
	RegistryYear     int64       `json:"registry_year"`
	RegistryNumber   int64       `json:"registry_number"`
	CourseDateStart  pgtype.Date `json:"course_date_start"`
	CourseDateEnd    pgtype.Date `json:"course_date_end"`
	LanguageCode     string      `json:"language_code"`
	ExpiryDate       interface{} `json:"expiry_date"`
}

func (q *Queries) ListCertificatesByCourseID(ctx context.Context, arg ListCertificatesByCourseIDParams) ([]ListCertificatesByCourseIDRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesByCourseID,
		arg.CourseID,
		arg.DateFrom,
		arg.DateTo,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesByCourseIDRow{}
	for rows.Next() {
		var i ListCertificatesByCourseIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.StudentFirstname,
			&i.StudentLastname,
			&i.CompanyName,
			&i.CourseName,
			&i.CourseSymbol,
			&i.RegistryYear,
			&i.RegistryNumber,
			&i.CourseDateStart,
			&i.CourseDateEnd,
			&i.LanguageCode,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByStudentID = `-- name: ListCertificatesByStudentID :many
  SELECT
      c.id,
      c.date,
	      c.course_name_snapshot AS course_name,
	      c.course_symbol_snapshot AS course_symbol,
      r.year AS registry_year,
      r.number::bigint AS registry_number,
      c.coursedatestart AS course_date_start,
      c.coursedateend AS course_date_end,
      COALESCE(CASE
          WHEN c.coursedateend IS NOT NULL
	              AND c.course_expiry_time_snapshot IS NOT NULL
	              AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
	          THEN TO_CHAR(c.coursedateend + c.course_expiry_time_snapshot::int * 365, 'YYYY-MM-DD')
          ELSE NULL::text
      END, '') AS expiry_date
  FROM certificates c
  JOIN registries r ON r.id = c.registry_id
  WHERE c.student_id = $1
  AND c.deleted_at IS NULL
  ORDER BY c.date DESC, c.id DESC
`

type ListCertificatesByStudentIDRow struct {
	ID              int64       `json:"id"`
	Date            pgtype.Date `json:"date"`
	CourseName      string      `json:"course_name"`
	CourseSymbol    string      `json:"course_symbol"`
	RegistryYear    int64       `json:"registry_year"`
	RegistryNumber  int64       `json:"registry_number"`
	CourseDateStart pgtype.Date `json:"course_date_start"`
	CourseDateEnd   pgtype.Date `json:"course_date_end"`
	ExpiryDate      interface{} `json:"expiry_date"`
}

func (q *Queries) ListCertificatesByStudentID(ctx context.Context, studentID int32) ([]ListCertificatesByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesByStudentIDRow{}
	for rows.Next() {
		var i ListCertificatesByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.CourseName,
			&i.CourseSymbol,
			&i.RegistryYear,
			&i.RegistryNumber,
			&i.CourseDateStart,
			&i.CourseDateEnd,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCertificate = `-- name: SoftDeleteCertificate :one
  UPDATE certificates
  SET
      deleted_at = now(),
      deleted_by_user_id = $2,
      delete_reason = $3
  WHERE id = $1
    AND deleted_at IS NULL
  RETURNING id
`

type SoftDeleteCertificateParams struct {
	ID              int64       `json:"id"`
	DeletedByUserID pgtype.Int8 `json:"deleted_by_user_id"`
	DeleteReason    pgtype.Text `json:"delete_reason"`
}

func (q *Queries) SoftDeleteCertificate(ctx context.Context, arg SoftDeleteCertificateParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteCertificate, arg.ID, arg.DeletedByUserID, arg.DeleteReason)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateCertificate = `-- name: UpdateCertificate :one
WITH updated AS (
    UPDATE certificates AS c
    SET
        date = $1,
        student_id = $2,
        coursedatestart = $3,
        coursedateend = $4,
        student_firstname_snapshot = $5,
        student_secondname_snapshot = $6,
        student_lastname_snapshot = $7,
        student_birthdate_snapshot = $8,
        student_birthplace_snapshot = $9,
        student_pesel_snapshot = $10,
        company_name_snapshot = $11
    WHERE c.id = $12
      AND c.deleted_at IS NULL
    RETURNING c.id
)
SELECT
    c.id,
    c.date,
    c.student_id,
    c.student_firstname_snapshot AS student_firstname,
    c.student_secondname_snapshot AS student_secondname,
    c.student_lastname_snapshot AS student_lastname,
    c.student_birthdate_snapshot AS student_birthdate,
    c.student_birthplace_snapshot AS student_birthplace,
    c.student_pesel_snapshot AS student_pesel,
    c.company_name_snapshot AS company_name,
    c.coursedatestart AS course_date_start,
    c.coursedateend AS course_date_end,
    r.id AS registry_id,
    r.year AS registry_year,
    r.number::bigint AS registry_number,
    r.course_id AS course_id,
    c.course_name_snapshot AS course_name,
    c.course_symbol_snapshot AS course_symbol,
    c.course_expiry_time_snapshot AS course_expiry_time,
    c.course_program_snapshot::text AS course_program,
    c.cert_front_page_snapshot AS cert_front_page,
    c.language_code,
    tja.id AS journal_attendee_id,
    tj.id AS journal_id,
    tj.title AS journal_title,
    tj.status AS journal_status,
    COALESCE(
        CASE
            WHEN c.coursedateend IS NOT NULL
                AND c.course_expiry_time_snapshot IS NOT NULL
                AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
            THEN TO_CHAR(c.coursedateend + c.course_expiry_time_snapshot::int * 365, 'YYYY-MM-DD')
            ELSE NULL::text
        END,
        ''
    ) AS expiry_date
FROM updated u
JOIN certificates c ON c.id = u.id
LEFT JOIN training_journal_attendees tja ON tja.certificate_id = c.id
LEFT JOIN training_journals tj ON tj.id = tja.journal_id
JOIN registries r ON r.id = c.registry_id
`

type UpdateCertificateParams struct {
	Date                      pgtype.Date `json:"date"`
	StudentID                 int32       `json:"student_id"`
	CourseDateStart           pgtype.Date `json:"course_date_start"`
	CourseDateEnd             pgtype.Date `json:"course_date_end"`
	StudentFirstnameSnapshot  string      `json:"student_firstname_snapshot"`
	StudentSecondnameSnapshot pgtype.Text `json:"student_secondname_snapshot"`
	StudentLastnameSnapshot   string      `json:"student_lastname_snapshot"`
	StudentBirthdateSnapshot  pgtype.Date `json:"student_birthdate_snapshot"`
	StudentBirthplaceSnapshot string      `json:"student_birthplace_snapshot"`
	StudentPeselSnapshot      pgtype.Text `json:"student_pesel_snapshot"`
	CompanyNameSnapshot       pgtype.Text `json:"company_name_snapshot"`
	CertificateID             int64       `json:"certificate_id"`
}

type UpdateCertificateRow struct {
	ID                int64       `json:"id"`
	Date              pgtype.Date `json:"date"`
	StudentID         int32       `json:"student_id"`
	StudentFirstname  string      `json:"student_firstname"`
	StudentSecondname pgtype.Text `json:"student_secondname"`
	StudentLastname   string      `json:"student_lastname"`
	StudentBirthdate  pgtype.Date `json:"student_birthdate"`
	StudentBirthplace string      `json:"student_birthplace"`
	StudentPesel      pgtype.Text `json:"student_pesel"`
	CompanyName       pgtype.Text `json:"company_name"`
	CourseDateStart   pgtype.Date `json:"course_date_start"`
	CourseDateEnd     pgtype.Date `json:"course_date_end"`
	RegistryID        int64       `json:"registry_id"`
	RegistryYear      int64       `json:"registry_year"`
	RegistryNumber    int64       `json:"registry_number"`
	CourseID          int64       `json:"course_id"`
	CourseName        string      `json:"course_name"`
	CourseSymbol      string      `json:"course_symbol"`
	CourseExpiryTime  pgtype.Text `json:"course_expiry_time"`
	CourseProgram     string      `json:"course_program"`
	CertFrontPage     string      `json:"cert_front_page"`
	LanguageCode      string      `json:"language_code"`
	JournalAttendeeID pgtype.Int8 `json:"journal_attendee_id"`
	JournalID         pgtype.Int8 `json:"journal_id"`
	JournalTitle      pgtype.Text `json:"journal_title"`
	JournalStatus     pgtype.Text `json:"journal_status"`
	ExpiryDate        interface{} `json:"expiry_date"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (UpdateCertificateRow, error) {
	row := q.db.QueryRow(ctx, updateCertificate,
		arg.Date,
		arg.StudentID,
		arg.CourseDateStart,
		arg.CourseDateEnd,
		arg.StudentFirstnameSnapshot,
		arg.StudentSecondnameSnapshot,
		arg.StudentLastnameSnapshot,
		arg.StudentBirthdateSnapshot,
		arg.StudentBirthplaceSnapshot,
		arg.StudentPeselSnapshot,
		arg.CompanyNameSnapshot,
		arg.CertificateID,
	)
	var i UpdateCertificateRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StudentID,
		&i.StudentFirstname,
		&i.StudentSecondname,
		&i.StudentLastname,
		&i.StudentBirthdate,
		&i.StudentBirthplace,
		&i.StudentPesel,
		&i.CompanyName,
		&i.CourseDateStart,
		&i.CourseDateEnd,
		&i.RegistryID,
		&i.RegistryYear,
		&i.RegistryNumber,
		&i.CourseID,
		&i.CourseName,
		&i.CourseSymbol,
		&i.CourseExpiryTime,
		&i.CourseProgram,
		&i.CertFrontPage,
		&i.LanguageCode,
		&i.JournalAttendeeID,
		&i.JournalID,
		&i.JournalTitle,
		&i.JournalStatus,
		&i.ExpiryDate,
	)
	return i, err
}
