// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificate_print_assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCertificatePrintAsset = `-- name: DeleteCertificatePrintAsset :execrows
  DELETE FROM certificate_print_assets
  WHERE kind = $1
`

func (q *Queries) DeleteCertificatePrintAsset(ctx context.Context, kind string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCertificatePrintAsset, kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCertificatePrintAssetFile = `-- name: GetCertificatePrintAssetFile :one
  SELECT
      kind,
      file_name,
      content_type,
      file_data,
      print_width_mm,
      updated_at
  FROM certificate_print_assets
  WHERE kind = $1
`

type GetCertificatePrintAssetFileRow struct {
	Kind         string             `json:"kind"`
	FileName     string             `json:"file_name"`
	ContentType  string             `json:"content_type"`
	FileData     []byte             `json:"file_data"`
	PrintWidthMm int16              `json:"print_width_mm"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCertificatePrintAssetFile(ctx context.Context, kind string) (GetCertificatePrintAssetFileRow, error) {
	row := q.db.QueryRow(ctx, getCertificatePrintAssetFile, kind)
	var i GetCertificatePrintAssetFileRow
	err := row.Scan(
		&i.Kind,
		&i.FileName,
		&i.ContentType,
		&i.FileData,
		&i.PrintWidthMm,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificatePrintAssetFiles = `-- name: ListCertificatePrintAssetFiles :many
  SELECT
      kind,
      content_type,
      file_data,
      print_width_mm
  FROM certificate_print_assets
  ORDER BY kind
`

type ListCertificatePrintAssetFilesRow struct {
	Kind         string `json:"kind"`
	ContentType  string `json:"content_type"`
	FileData     []byte `json:"file_data"`
	PrintWidthMm int16  `json:"print_width_mm"`
}

// ListCertificatePrintAssetFiles zwraca bajty wszystkich nadruków jednym zapytaniem -
// wydruk potrzebuje ich naraz, a rodzajów jest najwyżej trzy.
func (q *Queries) ListCertificatePrintAssetFiles(ctx context.Context) ([]ListCertificatePrintAssetFilesRow, error) {
	rows, err := q.db.Query(ctx, listCertificatePrintAssetFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatePrintAssetFilesRow{}
	for rows.Next() {
		var i ListCertificatePrintAssetFilesRow
		if err := rows.Scan(
			&i.Kind,
			&i.ContentType,
			&i.FileData,
			&i.PrintWidthMm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatePrintAssetsMeta = `-- name: ListCertificatePrintAssetsMeta :many
  SELECT
      id,
      kind,
      file_name,
      content_type,
      file_size,
      print_width_mm,
      uploaded_by_user_id,
      created_at,
      updated_at
  FROM certificate_print_assets
  ORDER BY kind
`

type ListCertificatePrintAssetsMetaRow struct {
	ID               int64              `json:"id"`
	Kind             string             `json:"kind"`
	FileName         string             `json:"file_name"`
	ContentType      string             `json:"content_type"`
	FileSize         int64              `json:"file_size"`
	PrintWidthMm     int16              `json:"print_width_mm"`
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCertificatePrintAssetsMeta(ctx context.Context) ([]ListCertificatePrintAssetsMetaRow, error) {
	rows, err := q.db.Query(ctx, listCertificatePrintAssetsMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatePrintAssetsMetaRow{}
	for rows.Next() {
		var i ListCertificatePrintAssetsMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FileName,
			&i.ContentType,
			&i.FileSize,
			&i.PrintWidthMm,
			&i.UploadedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCertificatePrintAsset = `-- name: UpsertCertificatePrintAsset :one
  INSERT INTO certificate_print_assets (
      kind,
      file_name,
      content_type,
      file_size,
      file_data,
      print_width_mm,
      uploaded_by_user_id
  ) VALUES (
      $1, $2, $3, $4, $5, $6, $7
  )
  ON CONFLICT (kind) DO UPDATE
  SET
      file_name = EXCLUDED.file_name,
      content_type = EXCLUDED.content_type,
      file_size = EXCLUDED.file_size,
      file_data = EXCLUDED.file_data,
      print_width_mm = EXCLUDED.print_width_mm,
      uploaded_by_user_id = EXCLUDED.uploaded_by_user_id,
      updated_at = now()
  RETURNING
      id,
      kind,
      file_name,
      content_type,
      file_size,
      print_width_mm,
      uploaded_by_user_id,
      created_at,
      updated_at
`

type UpsertCertificatePrintAssetParams struct {
	Kind             string `json:"kind"`
	FileName         string `json:"file_name"`
	ContentType      string `json:"content_type"`
	FileSize         int64  `json:"file_size"`
	FileData         []byte `json:"file_data"`
	PrintWidthMm     int16  `json:"print_width_mm"`
	UploadedByUserID int64  `json:"uploaded_by_user_id"`
}

type UpsertCertificatePrintAssetRow struct {
	ID               int64              `json:"id"`
	Kind             string             `json:"kind"`
	FileName         string             `json:"file_name"`
	ContentType      string             `json:"content_type"`
	FileSize         int64              `json:"file_size"`
	PrintWidthMm     int16              `json:"print_width_mm"`
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertCertificatePrintAsset(ctx context.Context, arg UpsertCertificatePrintAssetParams) (UpsertCertificatePrintAssetRow, error) {
	row := q.db.QueryRow(ctx, upsertCertificatePrintAsset,
		arg.Kind,
		arg.FileName,
		arg.ContentType,
		arg.FileSize,
		arg.FileData,
		arg.PrintWidthMm,
		arg.UploadedByUserID,
	)
	var i UpsertCertificatePrintAssetRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FileName,
		&i.ContentType,
		&i.FileSize,
		&i.PrintWidthMm,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
