// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
    date,
    student_id,
    coursedatestart,
    coursedateend,
    registry_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id
`

type CreateCertificateParams struct {
	Date            pgtype.Date `json:"date"`
	StudentID       int32       `json:"student_id"`
	Coursedatestart pgtype.Date `json:"coursedatestart"`
	Coursedateend   pgtype.Date `json:"coursedateend"`
	RegistryID      int64       `json:"registry_id"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.Date,
		arg.StudentID,
		arg.Coursedatestart,
		arg.Coursedateend,
		arg.RegistryID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT
    c.id,
    c.date,
    s.id AS student_id,
    s.firstname AS student_firstname,
    s.secondname AS student_secondname,
    s.lastname AS student_lastname,
    s.birthdate AS student_birthdate,
    s.birthplace AS student_birthplace,
    s.pesel AS student_pesel,
    comp.id AS company_id,
    comp.name AS company_name,
    c.coursedatestart AS course_date_start,
    c.coursedateend AS course_date_end,
    r.id AS registry_id,
    r.year AS registry_year,
    r.number::bigint AS registry_number,
    cr.id AS course_id,
    cr.mainname AS course_mainname,
    cr.name AS course_name,
    cr.symbol AS course_symbol,
    cr.expirytime AS course_expiry_time,
    cr.courseprogram::text AS course_program,
    cr.certfrontpage AS cert_front_page,
    tja.id AS journal_attendee_id,
    tj.id AS journal_id,
    tj.title AS journal_title,
    tj.status AS journal_status,
    COALESCE(CASE
        WHEN c.coursedateend IS NOT NULL
            AND cr.expirytime IS NOT NULL
            AND cr.expirytime ~ '^[0-9]+$'
        THEN TO_CHAR(c.coursedateend + cr.expirytime::int * 365, 'YYYY-MM-DD')
        ELSE NULL::text
    END, '') AS expiry_date
FROM certificates c
JOIN students s ON s.id = c.student_id
LEFT JOIN companies comp ON comp.id = s.company_id
LEFT JOIN training_journal_attendees tja ON tja.certificate_id = c.id
LEFT JOIN training_journals tj ON tj.id = tja.journal_id
JOIN registries r ON r.id = c.registry_id
JOIN courses cr ON cr.id = r.course_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCertificateByIDRow struct {
	ID                int64       `json:"id"`
	Date              pgtype.Date `json:"date"`
	StudentID         int64       `json:"student_id"`
	StudentFirstname  string      `json:"student_firstname"`
	StudentSecondname pgtype.Text `json:"student_secondname"`
	StudentLastname   string      `json:"student_lastname"`
	StudentBirthdate  pgtype.Date `json:"student_birthdate"`
	StudentBirthplace string      `json:"student_birthplace"`
	StudentPesel      pgtype.Text `json:"student_pesel"`
	CompanyID         pgtype.Int8 `json:"company_id"`
	CompanyName       pgtype.Text `json:"company_name"`
	CourseDateStart   pgtype.Date `json:"course_date_start"`
	CourseDateEnd     pgtype.Date `json:"course_date_end"`
	RegistryID        int64       `json:"registry_id"`
	RegistryYear      int64       `json:"registry_year"`
	RegistryNumber    int64       `json:"registry_number"`
	CourseID          int64       `json:"course_id"`
	CourseMainname    pgtype.Text `json:"course_mainname"`
	CourseName        string      `json:"course_name"`
	CourseSymbol      string      `json:"course_symbol"`
	CourseExpiryTime  pgtype.Text `json:"course_expiry_time"`
	CourseProgram     string      `json:"course_program"`
	CertFrontPage     pgtype.Text `json:"cert_front_page"`
	JournalAttendeeID pgtype.Int8 `json:"journal_attendee_id"`
	JournalID         pgtype.Int8 `json:"journal_id"`
	JournalTitle      pgtype.Text `json:"journal_title"`
	JournalStatus     pgtype.Text `json:"journal_status"`
	ExpiryDate        interface{} `json:"expiry_date"`
}

func (q *Queries) GetCertificateByID(ctx context.Context, id int64) (GetCertificateByIDRow, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, id)
	var i GetCertificateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StudentID,
		&i.StudentFirstname,
		&i.StudentSecondname,
		&i.StudentLastname,
		&i.StudentBirthdate,
		&i.StudentBirthplace,
		&i.StudentPesel,
		&i.CompanyID,
		&i.CompanyName,
		&i.CourseDateStart,
		&i.CourseDateEnd,
		&i.RegistryID,
		&i.RegistryYear,
		&i.RegistryNumber,
		&i.CourseID,
		&i.CourseMainname,
		&i.CourseName,
		&i.CourseSymbol,
		&i.CourseExpiryTime,
		&i.CourseProgram,
		&i.CertFrontPage,
		&i.JournalAttendeeID,
		&i.JournalID,
		&i.JournalTitle,
		&i.JournalStatus,
		&i.ExpiryDate,
	)
	return i, err
}

const listCertificates = `-- name: ListCertificates :many
  SELECT
      c.id,
      c.date,
      s.firstname AS student_firstname,
      s.lastname AS student_lastname,
      comp.name AS company_name,
      cr.name AS course_name,
      cr.symbol AS course_symbol,
      r.year AS registry_year,
      r.number::bigint AS registry_number,
      c.coursedatestart AS course_date_start,
      c.coursedateend AS course_date_end,
      COALESCE(CASE
          WHEN c.coursedateend IS NOT NULL
              AND cr.expirytime IS NOT NULL
              AND cr.expirytime ~ '^[0-9]+$'
          THEN TO_CHAR(c.coursedateend + cr.expirytime::int * 365, 'YYYY-MM-DD')
          ELSE NULL::text
      END, '') AS expiry_date
  FROM certificates c
  JOIN students s ON s.id = c.student_id
  LEFT JOIN companies comp ON comp.id = s.company_id
  JOIN registries r ON r.id = c.registry_id
  JOIN courses cr ON cr.id = r.course_id
  WHERE
      (
          $1::text IS NULL
          OR COALESCE(s.firstname, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(s.lastname, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(comp.name, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(cr.name, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(cr.symbol, '') ILIKE '%' || $1::text || '%'
          OR (
              r.number::bigint::text || '/' || cr.symbol || '/' || r.year::text
          ) ILIKE '%' || $1::text || '%'
      )
      AND c.deleted_at IS NULL
  ORDER BY c.date DESC, c.id DESC
  LIMIT $2
`

type ListCertificatesParams struct {
	Search     pgtype.Text `json:"search"`
	LimitCount int32       `json:"limit_count"`
}

type ListCertificatesRow struct {
	ID               int64       `json:"id"`
	Date             pgtype.Date `json:"date"`
	StudentFirstname string      `json:"student_firstname"`
	StudentLastname  string      `json:"student_lastname"`
	CompanyName      pgtype.Text `json:"company_name"`
	CourseName       string      `json:"course_name"`
	CourseSymbol     string      `json:"course_symbol"`
	RegistryYear     int64       `json:"registry_year"`
	RegistryNumber   int64       `json:"registry_number"`
	CourseDateStart  pgtype.Date `json:"course_date_start"`
	CourseDateEnd    pgtype.Date `json:"course_date_end"`
	ExpiryDate       interface{} `json:"expiry_date"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listCertificates, arg.Search, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesRow{}
	for rows.Next() {
		var i ListCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.StudentFirstname,
			&i.StudentLastname,
			&i.CompanyName,
			&i.CourseName,
			&i.CourseSymbol,
			&i.RegistryYear,
			&i.RegistryNumber,
			&i.CourseDateStart,
			&i.CourseDateEnd,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByStudentID = `-- name: ListCertificatesByStudentID :many
  SELECT
      c.id,
      c.date,
      cr.name AS course_name,
      cr.symbol AS course_symbol,
      r.year AS registry_year,
      r.number::bigint AS registry_number,
      c.coursedatestart AS course_date_start,
      c.coursedateend AS course_date_end,
      COALESCE(CASE
          WHEN c.coursedateend IS NOT NULL
              AND cr.expirytime IS NOT NULL
              AND cr.expirytime ~ '^[0-9]+$'
          THEN TO_CHAR(c.coursedateend + cr.expirytime::int * 365, 'YYYY-MM-DD')
          ELSE NULL::text
      END, '') AS expiry_date
  FROM certificates c
  JOIN registries r ON r.id = c.registry_id
  JOIN courses cr ON cr.id = r.course_id
  WHERE c.student_id = $1
  AND c.deleted_at IS NULL
  ORDER BY c.date DESC, c.id DESC
`

type ListCertificatesByStudentIDRow struct {
	ID              int64       `json:"id"`
	Date            pgtype.Date `json:"date"`
	CourseName      string      `json:"course_name"`
	CourseSymbol    string      `json:"course_symbol"`
	RegistryYear    int64       `json:"registry_year"`
	RegistryNumber  int64       `json:"registry_number"`
	CourseDateStart pgtype.Date `json:"course_date_start"`
	CourseDateEnd   pgtype.Date `json:"course_date_end"`
	ExpiryDate      interface{} `json:"expiry_date"`
}

func (q *Queries) ListCertificatesByStudentID(ctx context.Context, studentID int32) ([]ListCertificatesByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesByStudentIDRow{}
	for rows.Next() {
		var i ListCertificatesByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.CourseName,
			&i.CourseSymbol,
			&i.RegistryYear,
			&i.RegistryNumber,
			&i.CourseDateStart,
			&i.CourseDateEnd,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCertificate = `-- name: SoftDeleteCertificate :one
  UPDATE certificates
  SET
      deleted_at = now(),
      deleted_by_user_id = $2,
      delete_reason = $3
  WHERE id = $1
    AND deleted_at IS NULL
  RETURNING id
`

type SoftDeleteCertificateParams struct {
	ID              int64       `json:"id"`
	DeletedByUserID pgtype.Int8 `json:"deleted_by_user_id"`
	DeleteReason    pgtype.Text `json:"delete_reason"`
}

func (q *Queries) SoftDeleteCertificate(ctx context.Context, arg SoftDeleteCertificateParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteCertificate, arg.ID, arg.DeletedByUserID, arg.DeleteReason)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateCertificate = `-- name: UpdateCertificate :one
  WITH updated AS (
      UPDATE certificates AS c
      SET
          date = $1,
          student_id = $2,
          coursedatestart = $3,
          coursedateend = $4
      WHERE c.id = $5
      AND c.deleted_at IS NULL
      RETURNING c.id
  )
  SELECT
      c.id,
      c.date,
      s.id AS student_id,
      s.firstname AS student_firstname,
      s.secondname AS student_secondname,
      s.lastname AS student_lastname,
      s.birthdate AS student_birthdate,
      s.birthplace AS student_birthplace,
      s.pesel AS student_pesel,
      comp.id AS company_id,
      comp.name AS company_name,
      c.coursedatestart AS course_date_start,
      c.coursedateend AS course_date_end,
      r.id AS registry_id,
      r.year AS registry_year,
      r.number::bigint AS registry_number,
      cr.id AS course_id,
      cr.mainname AS course_mainname,
      cr.name AS course_name,
      cr.symbol AS course_symbol,
      cr.expirytime AS course_expiry_time,
      cr.courseprogram::text AS course_program,
      cr.certfrontpage AS cert_front_page,
      tja.id AS journal_attendee_id,
      tj.id AS journal_id,
      tj.title AS journal_title,
      tj.status AS journal_status,
      COALESCE(CASE
          WHEN c.coursedateend IS NOT NULL
              AND cr.expirytime IS NOT NULL
              AND cr.expirytime ~ '^[0-9]+$'
          THEN TO_CHAR(c.coursedateend + cr.expirytime::int * 365, 'YYYY-MM-DD')
          ELSE NULL::text
      END, '') AS expiry_date
  FROM updated u
  JOIN certificates c ON c.id = u.id
  JOIN students s ON s.id = c.student_id
  LEFT JOIN training_journal_attendees tja ON tja.certificate_id = c.id
  LEFT JOIN training_journals tj ON tj.id = tja.journal_id
  LEFT JOIN companies comp ON comp.id = s.company_id
  JOIN registries r ON r.id = c.registry_id
  JOIN courses cr ON cr.id = r.course_id
`

type UpdateCertificateParams struct {
	Date            pgtype.Date `json:"date"`
	StudentID       int32       `json:"student_id"`
	CourseDateStart pgtype.Date `json:"course_date_start"`
	CourseDateEnd   pgtype.Date `json:"course_date_end"`
	CertificateID   int64       `json:"certificate_id"`
}

type UpdateCertificateRow struct {
	ID                int64       `json:"id"`
	Date              pgtype.Date `json:"date"`
	StudentID         int64       `json:"student_id"`
	StudentFirstname  string      `json:"student_firstname"`
	StudentSecondname pgtype.Text `json:"student_secondname"`
	StudentLastname   string      `json:"student_lastname"`
	StudentBirthdate  pgtype.Date `json:"student_birthdate"`
	StudentBirthplace string      `json:"student_birthplace"`
	StudentPesel      pgtype.Text `json:"student_pesel"`
	CompanyID         pgtype.Int8 `json:"company_id"`
	CompanyName       pgtype.Text `json:"company_name"`
	CourseDateStart   pgtype.Date `json:"course_date_start"`
	CourseDateEnd     pgtype.Date `json:"course_date_end"`
	RegistryID        int64       `json:"registry_id"`
	RegistryYear      int64       `json:"registry_year"`
	RegistryNumber    int64       `json:"registry_number"`
	CourseID          int64       `json:"course_id"`
	CourseMainname    pgtype.Text `json:"course_mainname"`
	CourseName        string      `json:"course_name"`
	CourseSymbol      string      `json:"course_symbol"`
	CourseExpiryTime  pgtype.Text `json:"course_expiry_time"`
	CourseProgram     string      `json:"course_program"`
	CertFrontPage     pgtype.Text `json:"cert_front_page"`
	JournalAttendeeID pgtype.Int8 `json:"journal_attendee_id"`
	JournalID         pgtype.Int8 `json:"journal_id"`
	JournalTitle      pgtype.Text `json:"journal_title"`
	JournalStatus     pgtype.Text `json:"journal_status"`
	ExpiryDate        interface{} `json:"expiry_date"`
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (UpdateCertificateRow, error) {
	row := q.db.QueryRow(ctx, updateCertificate,
		arg.Date,
		arg.StudentID,
		arg.CourseDateStart,
		arg.CourseDateEnd,
		arg.CertificateID,
	)
	var i UpdateCertificateRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StudentID,
		&i.StudentFirstname,
		&i.StudentSecondname,
		&i.StudentLastname,
		&i.StudentBirthdate,
		&i.StudentBirthplace,
		&i.StudentPesel,
		&i.CompanyID,
		&i.CompanyName,
		&i.CourseDateStart,
		&i.CourseDateEnd,
		&i.RegistryID,
		&i.RegistryYear,
		&i.RegistryNumber,
		&i.CourseID,
		&i.CourseMainname,
		&i.CourseName,
		&i.CourseSymbol,
		&i.CourseExpiryTime,
		&i.CourseProgram,
		&i.CertFrontPage,
		&i.JournalAttendeeID,
		&i.JournalID,
		&i.JournalTitle,
		&i.JournalStatus,
		&i.ExpiryDate,
	)
	return i, err
}
