// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
  INSERT INTO companies (
      name,
      street,
      city,
      zipcode,
      nip,
      email,
      contactperson,
      telephoneno,
      note
  ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9
  )
  RETURNING
      id,
      name,
      street,
      city,
      zipcode,
      nip,
      email,
      contactperson,
      telephoneno,
      note
`

type CreateCompanyParams struct {
	Name          string      `json:"name"`
	Street        string      `json:"street"`
	City          string      `json:"city"`
	Zipcode       string      `json:"zipcode"`
	Nip           string      `json:"nip"`
	Email         pgtype.Text `json:"email"`
	Contactperson pgtype.Text `json:"contactperson"`
	Telephoneno   string      `json:"telephoneno"`
	Note          pgtype.Text `json:"note"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Zipcode,
		arg.Nip,
		arg.Email,
		arg.Contactperson,
		arg.Telephoneno,
		arg.Note,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Zipcode,
		&i.Nip,
		&i.Email,
		&i.Contactperson,
		&i.Telephoneno,
		&i.Note,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
  SELECT
      id,
      name,
      street,
      city,
      zipcode,
      nip,
      email,
      contactperson,
      telephoneno,
      note
  FROM companies
  WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Zipcode,
		&i.Nip,
		&i.Email,
		&i.Contactperson,
		&i.Telephoneno,
		&i.Note,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT
      id,
      name,
      city,
      nip,
      contactperson,
      telephoneno
  FROM companies
  WHERE
      (
          $1::text IS NULL
          OR COALESCE(name, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(city, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(nip, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(contactperson, '') ILIKE '%' || $1::text || '%'
      )
  ORDER BY name, city
  LIMIT $2
`

type ListCompaniesParams struct {
	Search     pgtype.Text `json:"search"`
	LimitCount int32       `json:"limit_count"`
}

type ListCompaniesRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	City          string      `json:"city"`
	Nip           string      `json:"nip"`
	Contactperson pgtype.Text `json:"contactperson"`
	Telephoneno   string      `json:"telephoneno"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Search, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Nip,
			&i.Contactperson,
			&i.Telephoneno,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
  UPDATE companies
  SET
      name = $2,
      street = $3,  
      city = $4,
      zipcode = $5,
      nip = $6,
      email = $7,
      contactperson = $8,
      telephoneno = $9,
      note = $10
  WHERE id = $1
  RETURNING
      id,
      name,
      street,
      city,
      zipcode,
      nip,
      email,
      contactperson,
      telephoneno,
      note
`

type UpdateCompanyParams struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Street        string      `json:"street"`
	City          string      `json:"city"`
	Zipcode       string      `json:"zipcode"`
	Nip           string      `json:"nip"`
	Email         pgtype.Text `json:"email"`
	Contactperson pgtype.Text `json:"contactperson"`
	Telephoneno   string      `json:"telephoneno"`
	Note          pgtype.Text `json:"note"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Zipcode,
		arg.Nip,
		arg.Email,
		arg.Contactperson,
		arg.Telephoneno,
		arg.Note,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Zipcode,
		&i.Nip,
		&i.Email,
		&i.Contactperson,
		&i.Telephoneno,
		&i.Note,
	)
	return i, err
}
