// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
  INSERT INTO courses (
      mainname,
      name,
      symbol,
      expirytime,
      courseprogram,
      certfrontpage
  ) VALUES (
      $1, $2, $3, $4, $5, $6
  )
  RETURNING
      id,
      mainname,
      name,
      symbol,
      expirytime,
      courseprogram,
      certfrontpage,
      updated_at,
      delivered_by_platform
`

type CreateCourseParams struct {
	Mainname      pgtype.Text `json:"mainname"`
	Name          string      `json:"name"`
	Symbol        string      `json:"symbol"`
	Expirytime    pgtype.Text `json:"expirytime"`
	Courseprogram []byte      `json:"courseprogram"`
	Certfrontpage pgtype.Text `json:"certfrontpage"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Mainname,
		arg.Name,
		arg.Symbol,
		arg.Expirytime,
		arg.Courseprogram,
		arg.Certfrontpage,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Mainname,
		&i.Name,
		&i.Symbol,
		&i.Expirytime,
		&i.Courseprogram,
		&i.Certfrontpage,
		&i.UpdatedAt,
		&i.DeliveredByPlatform,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, mainname, name, symbol, expirytime, courseprogram, certfrontpage, updated_at, delivered_by_platform FROM courses
WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Mainname,
		&i.Name,
		&i.Symbol,
		&i.Expirytime,
		&i.Courseprogram,
		&i.Certfrontpage,
		&i.UpdatedAt,
		&i.DeliveredByPlatform,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
    id,
    mainname,
    name,
    symbol,
    expirytime,
    delivered_by_platform,
    COUNT(*) OVER () AS total_count
FROM courses
WHERE
    (
        $1::text IS NULL
        OR COALESCE(mainname, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(name, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(symbol, '') ILIKE '%' || $1::text || '%'
    )
    AND ($2::timestamptz IS NULL OR updated_at > $2::timestamptz)
    AND ($3::boolean IS NULL OR delivered_by_platform = $3::boolean)
ORDER BY
    CASE
        WHEN $1::text IS NULL THEN 5
        WHEN LOWER(COALESCE(symbol, '')) = LOWER($1::text) THEN 0
        WHEN LOWER(COALESCE(symbol, '')) LIKE LOWER($1::text) || '%' THEN 1
        WHEN LOWER(COALESCE(name, '')) LIKE LOWER($1::text) || '%' THEN 2
        WHEN LOWER(COALESCE(mainname, '')) LIKE LOWER($1::text) || '%' THEN 3
        WHEN LOWER(COALESCE(symbol, '')) LIKE '%' || LOWER($1::text) || '%' THEN 4
        ELSE 5
    END,
    symbol,
    name,
    id
LIMIT $5
OFFSET $4
`

type ListCoursesParams struct {
	Search              pgtype.Text        `json:"search"`
	UpdatedSince        pgtype.Timestamptz `json:"updated_since"`
	DeliveredByPlatform pgtype.Bool        `json:"delivered_by_platform"`
	OffsetCount         int32              `json:"offset_count"`
	LimitCount          int32              `json:"limit_count"`
}

type ListCoursesRow struct {
	ID                  int64       `json:"id"`
	Mainname            pgtype.Text `json:"mainname"`
	Name                string      `json:"name"`
	Symbol              string      `json:"symbol"`
	Expirytime          pgtype.Text `json:"expirytime"`
	DeliveredByPlatform bool        `json:"delivered_by_platform"`
	TotalCount          int64       `json:"total_count"`
}

// total_count to liczba wszystkich kursów spełniających filtry (dla koperty pagination).
func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Search,
		arg.UpdatedSince,
		arg.DeliveredByPlatform,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Mainname,
			&i.Name,
			&i.Symbol,
			&i.Expirytime,
			&i.DeliveredByPlatform,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesDetails = `-- name: ListCoursesDetails :many
SELECT
    c.id,
    c.mainname,
    c.name,
    c.symbol,
    c.expirytime,
    c.courseprogram,
    c.certfrontpage,
    COALESCE(t.translations, '[]'::json)::json AS certificate_translations,
    COUNT(*) OVER () AS total_count
FROM courses c
LEFT JOIN LATERAL (
    SELECT json_agg(
        json_build_object(
            'languageCode', ct.language_code,
            'courseName', ct.course_name,
            -- ::text, bo CourseProgram w DTO jest stringiem niosącym JSON,
            -- tak samo jak w ścieżce pojedynczego kursu.
            'courseProgram', ct.course_program::text,
            'certFrontPage', ct.cert_front_page
        )
        ORDER BY ct.language_code
    ) AS translations
    FROM course_certificate_translations ct
    WHERE ct.course_id = c.id
) t ON TRUE
WHERE
    (
        $1::text IS NULL
        OR COALESCE(c.mainname, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(c.name, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(c.symbol, '') ILIKE '%' || $1::text || '%'
    )
    AND ($2::timestamptz IS NULL OR c.updated_at > $2::timestamptz)
    AND ($3::boolean IS NULL OR c.delivered_by_platform = $3::boolean)
ORDER BY
    CASE
        WHEN $1::text IS NULL THEN 5
        WHEN LOWER(COALESCE(c.symbol, '')) = LOWER($1::text) THEN 0
        WHEN LOWER(COALESCE(c.symbol, '')) LIKE LOWER($1::text) || '%' THEN 1
        WHEN LOWER(COALESCE(c.name, '')) LIKE LOWER($1::text) || '%' THEN 2
        WHEN LOWER(COALESCE(c.mainname, '')) LIKE LOWER($1::text) || '%' THEN 3
        WHEN LOWER(COALESCE(c.symbol, '')) LIKE '%' || LOWER($1::text) || '%' THEN 4
        ELSE 5
    END,
    c.symbol,
    c.name,
    c.id
LIMIT $5
OFFSET $4
`

type ListCoursesDetailsParams struct {
	Search              pgtype.Text        `json:"search"`
	UpdatedSince        pgtype.Timestamptz `json:"updated_since"`
	DeliveredByPlatform pgtype.Bool        `json:"delivered_by_platform"`
	OffsetCount         int32              `json:"offset_count"`
	LimitCount          int32              `json:"limit_count"`
}

type ListCoursesDetailsRow struct {
	ID                      int64       `json:"id"`
	Mainname                pgtype.Text `json:"mainname"`
	Name                    string      `json:"name"`
	Symbol                  string      `json:"symbol"`
	Expirytime              pgtype.Text `json:"expirytime"`
	Courseprogram           []byte      `json:"courseprogram"`
	Certfrontpage           pgtype.Text `json:"certfrontpage"`
	CertificateTranslations []byte      `json:"certificate_translations"`
	TotalCount              int64       `json:"total_count"`
}

// To samo wyszukiwanie i ta sama kolejność co w ListCourses, ale z pełną
// treścią kursu: programem szkolenia, szablonem zaświadczenia i tłumaczeniami.
//
// Tłumaczenia wracają jako gotowa tablica JSON z kluczami odpowiadającymi
// tagom CourseCertificateTranslationDTO, więc kolumnę wystarczy odpakować
// json.Unmarshal-em wprost do CourseDetailDTO.CertificateTranslations - bez
// osobnego zapytania i bez pośrednich struktur.
//
// Kurs bez tłumaczeń dostaje '[]', nigdy NULL, żeby odpowiedź JSON zawsze
// miała tablicę.
//
// Wszystkie te kolumny potrafią być duże, więc po to zapytanie warto sięgać
// tylko wtedy, gdy treści są faktycznie potrzebne - do samej listy wystarczy
// ListCourses.
func (q *Queries) ListCoursesDetails(ctx context.Context, arg ListCoursesDetailsParams) ([]ListCoursesDetailsRow, error) {
	rows, err := q.db.Query(ctx, listCoursesDetails,
		arg.Search,
		arg.UpdatedSince,
		arg.DeliveredByPlatform,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesDetailsRow{}
	for rows.Next() {
		var i ListCoursesDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Mainname,
			&i.Name,
			&i.Symbol,
			&i.Expirytime,
			&i.Courseprogram,
			&i.Certfrontpage,
			&i.CertificateTranslations,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCourseDeliveredByPlatform = `-- name: SetCourseDeliveredByPlatform :one
UPDATE courses
SET delivered_by_platform = $1
WHERE id = $2
RETURNING delivered_by_platform
`

type SetCourseDeliveredByPlatformParams struct {
	DeliveredByPlatform bool  `json:"delivered_by_platform"`
	ID                  int64 `json:"id"`
}

func (q *Queries) SetCourseDeliveredByPlatform(ctx context.Context, arg SetCourseDeliveredByPlatformParams) (bool, error) {
	row := q.db.QueryRow(ctx, setCourseDeliveredByPlatform, arg.DeliveredByPlatform, arg.ID)
	var delivered_by_platform bool
	err := row.Scan(&delivered_by_platform)
	return delivered_by_platform, err
}

const updateCourse = `-- name: UpdateCourse :one
  UPDATE courses
  SET
      mainname = $2,
      name = $3,
      symbol = $4,
      expirytime = $5,
      courseprogram = $6,
      certfrontpage = $7
  WHERE id = $1
  RETURNING id, mainname, name, symbol, expirytime, courseprogram, certfrontpage, updated_at, delivered_by_platform
`

type UpdateCourseParams struct {
	ID            int64       `json:"id"`
	Mainname      pgtype.Text `json:"mainname"`
	Name          string      `json:"name"`
	Symbol        string      `json:"symbol"`
	Expirytime    pgtype.Text `json:"expirytime"`
	Courseprogram []byte      `json:"courseprogram"`
	Certfrontpage pgtype.Text `json:"certfrontpage"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Mainname,
		arg.Name,
		arg.Symbol,
		arg.Expirytime,
		arg.Courseprogram,
		arg.Certfrontpage,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Mainname,
		&i.Name,
		&i.Symbol,
		&i.Expirytime,
		&i.Courseprogram,
		&i.Certfrontpage,
		&i.UpdatedAt,
		&i.DeliveredByPlatform,
	)
	return i, err
}
