// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
  INSERT INTO courses (
      mainname,
      name,
      symbol,
      expirytime,
      courseprogram,
      certfrontpage
  ) VALUES (
      $1, $2, $3, $4, $5, $6
  )
  RETURNING
      id,
      mainname,
      name,
      symbol,
      expirytime,
      courseprogram,
      certfrontpage
`

type CreateCourseParams struct {
	Mainname      pgtype.Text `json:"mainname"`
	Name          string      `json:"name"`
	Symbol        string      `json:"symbol"`
	Expirytime    pgtype.Text `json:"expirytime"`
	Courseprogram []byte      `json:"courseprogram"`
	Certfrontpage pgtype.Text `json:"certfrontpage"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Mainname,
		arg.Name,
		arg.Symbol,
		arg.Expirytime,
		arg.Courseprogram,
		arg.Certfrontpage,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Mainname,
		&i.Name,
		&i.Symbol,
		&i.Expirytime,
		&i.Courseprogram,
		&i.Certfrontpage,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, mainname, name, symbol, expirytime, courseprogram, certfrontpage FROM courses
WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Mainname,
		&i.Name,
		&i.Symbol,
		&i.Expirytime,
		&i.Courseprogram,
		&i.Certfrontpage,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
    id,
    mainname,
    name,
    symbol,
    expirytime
FROM courses
WHERE
    (
        $1::text IS NULL
        OR COALESCE(mainname, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(name, '') ILIKE '%' || $1::text || '%'
        OR COALESCE(symbol, '') ILIKE '%' || $1::text || '%'
    )
ORDER BY
    CASE
        WHEN $1::text IS NULL THEN 5
        WHEN LOWER(COALESCE(symbol, '')) = LOWER($1::text) THEN 0
        WHEN LOWER(COALESCE(symbol, '')) LIKE LOWER($1::text) || '%' THEN 1
        WHEN LOWER(COALESCE(name, '')) LIKE LOWER($1::text) || '%' THEN 2
        WHEN LOWER(COALESCE(mainname, '')) LIKE LOWER($1::text) || '%' THEN 3
        WHEN LOWER(COALESCE(symbol, '')) LIKE '%' || LOWER($1::text) || '%' THEN 4
        ELSE 5
    END,
    symbol,
    name
LIMIT $2
`

type ListCoursesParams struct {
	Search     pgtype.Text `json:"search"`
	LimitCount int32       `json:"limit_count"`
}

type ListCoursesRow struct {
	ID         int64       `json:"id"`
	Mainname   pgtype.Text `json:"mainname"`
	Name       string      `json:"name"`
	Symbol     string      `json:"symbol"`
	Expirytime pgtype.Text `json:"expirytime"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses, arg.Search, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Mainname,
			&i.Name,
			&i.Symbol,
			&i.Expirytime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
  UPDATE courses
  SET
      mainname = $2,
      name = $3,
      symbol = $4,
      expirytime = $5,
      courseprogram = $6,
      certfrontpage = $7
  WHERE id = $1
  RETURNING id, mainname, name, symbol, expirytime, courseprogram, certfrontpage
`

type UpdateCourseParams struct {
	ID            int64       `json:"id"`
	Mainname      pgtype.Text `json:"mainname"`
	Name          string      `json:"name"`
	Symbol        string      `json:"symbol"`
	Expirytime    pgtype.Text `json:"expirytime"`
	Courseprogram []byte      `json:"courseprogram"`
	Certfrontpage pgtype.Text `json:"certfrontpage"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Mainname,
		arg.Name,
		arg.Symbol,
		arg.Expirytime,
		arg.Courseprogram,
		arg.Certfrontpage,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Mainname,
		&i.Name,
		&i.Symbol,
		&i.Expirytime,
		&i.Courseprogram,
		&i.Certfrontpage,
	)
	return i, err
}
