// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_certificate_translations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCourseCertificateTranslation = `-- name: DeleteCourseCertificateTranslation :execrows
DELETE FROM course_certificate_translations
WHERE course_id = $1
  AND language_code = $2
`

type DeleteCourseCertificateTranslationParams struct {
	CourseID     int64  `json:"course_id"`
	LanguageCode string `json:"language_code"`
}

func (q *Queries) DeleteCourseCertificateTranslation(ctx context.Context, arg DeleteCourseCertificateTranslationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourseCertificateTranslation, arg.CourseID, arg.LanguageCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourseCertificateTranslationByCourseAndLanguage = `-- name: GetCourseCertificateTranslationByCourseAndLanguage :one
SELECT
    id,
    course_id,
    language_code,
    course_name,
    course_program::text AS course_program,
    cert_front_page,
    created_at,
    updated_at
FROM course_certificate_translations
WHERE course_id = $1
  AND language_code = $2
`

type GetCourseCertificateTranslationByCourseAndLanguageParams struct {
	CourseID     int64  `json:"course_id"`
	LanguageCode string `json:"language_code"`
}

type GetCourseCertificateTranslationByCourseAndLanguageRow struct {
	ID            int64              `json:"id"`
	CourseID      int64              `json:"course_id"`
	LanguageCode  string             `json:"language_code"`
	CourseName    string             `json:"course_name"`
	CourseProgram string             `json:"course_program"`
	CertFrontPage string             `json:"cert_front_page"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCourseCertificateTranslationByCourseAndLanguage(ctx context.Context, arg GetCourseCertificateTranslationByCourseAndLanguageParams) (GetCourseCertificateTranslationByCourseAndLanguageRow, error) {
	row := q.db.QueryRow(ctx, getCourseCertificateTranslationByCourseAndLanguage, arg.CourseID, arg.LanguageCode)
	var i GetCourseCertificateTranslationByCourseAndLanguageRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.LanguageCode,
		&i.CourseName,
		&i.CourseProgram,
		&i.CertFrontPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseCertificateTranslationsByCourseID = `-- name: ListCourseCertificateTranslationsByCourseID :many
SELECT
    id,
    course_id,
    language_code,
    course_name,
    course_program::text AS course_program,
    cert_front_page,
    created_at,
    updated_at
FROM course_certificate_translations
WHERE course_id = $1
ORDER BY language_code
`

type ListCourseCertificateTranslationsByCourseIDRow struct {
	ID            int64              `json:"id"`
	CourseID      int64              `json:"course_id"`
	LanguageCode  string             `json:"language_code"`
	CourseName    string             `json:"course_name"`
	CourseProgram string             `json:"course_program"`
	CertFrontPage string             `json:"cert_front_page"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCourseCertificateTranslationsByCourseID(ctx context.Context, courseID int64) ([]ListCourseCertificateTranslationsByCourseIDRow, error) {
	rows, err := q.db.Query(ctx, listCourseCertificateTranslationsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourseCertificateTranslationsByCourseIDRow{}
	for rows.Next() {
		var i ListCourseCertificateTranslationsByCourseIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.LanguageCode,
			&i.CourseName,
			&i.CourseProgram,
			&i.CertFrontPage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourseCertificateTranslation = `-- name: UpsertCourseCertificateTranslation :one
INSERT INTO course_certificate_translations (
    course_id,
    language_code,
    course_name,
    course_program,
    cert_front_page
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (course_id, language_code)
DO UPDATE SET
    course_name = EXCLUDED.course_name,
    course_program = EXCLUDED.course_program,
    cert_front_page = EXCLUDED.cert_front_page,
    updated_at = now()
RETURNING
    id,
    course_id,
    language_code,
    course_name,
    course_program::text AS course_program,
    cert_front_page,
    created_at,
    updated_at
`

type UpsertCourseCertificateTranslationParams struct {
	CourseID      int64  `json:"course_id"`
	LanguageCode  string `json:"language_code"`
	CourseName    string `json:"course_name"`
	CourseProgram []byte `json:"course_program"`
	CertFrontPage string `json:"cert_front_page"`
}

type UpsertCourseCertificateTranslationRow struct {
	ID            int64              `json:"id"`
	CourseID      int64              `json:"course_id"`
	LanguageCode  string             `json:"language_code"`
	CourseName    string             `json:"course_name"`
	CourseProgram string             `json:"course_program"`
	CertFrontPage string             `json:"cert_front_page"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertCourseCertificateTranslation(ctx context.Context, arg UpsertCourseCertificateTranslationParams) (UpsertCourseCertificateTranslationRow, error) {
	row := q.db.QueryRow(ctx, upsertCourseCertificateTranslation,
		arg.CourseID,
		arg.LanguageCode,
		arg.CourseName,
		arg.CourseProgram,
		arg.CertFrontPage,
	)
	var i UpsertCourseCertificateTranslationRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.LanguageCode,
		&i.CourseName,
		&i.CourseProgram,
		&i.CertFrontPage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
