// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
)

const countExpiringCertificates = `-- name: CountExpiringCertificates :one
SELECT COUNT(*) FROM certificates c
JOIN registries r ON c.registry_id = r.id
JOIN courses cr ON r.course_id = cr.id
WHERE c.coursedateend IS NOT NULL
  AND (c.coursedateend + cr.expirytime::int * 365) >= CURRENT_DATE
  AND (c.coursedateend + cr.expirytime::int * 365) < CURRENT_DATE + INTERVAL '30 days'
  AND c.deleted_at IS NULL
`

func (q *Queries) CountExpiringCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringCertificates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM students) AS total_students,
    (SELECT COUNT(*) FROM companies) AS total_companies,
    (SELECT COUNT(*) FROM certificates WHERE deleted_at IS NULL) AS total_certificates
`

type GetDashboardStatsRow struct {
	TotalStudents     int64 `json:"total_students"`
	TotalCompanies    int64 `json:"total_companies"`
	TotalCertificates int64 `json:"total_certificates"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalStudents, &i.TotalCompanies, &i.TotalCertificates)
	return i, err
}

const listExpiringCertificates = `-- name: ListExpiringCertificates :many
SELECT
    c.id,
    TO_CHAR(c.coursedateend + cr.expirytime::int * 365, 'YYYY-MM-DD') AS expiry_date,
    s.firstname,
    s.lastname,
    comp.name AS company_name,
    r.year,
    r.number,
    cr.name AS course_name,
    cr.symbol AS course_symbol
FROM certificates c
JOIN students s ON c.student_id = s.id
JOIN companies comp ON s.company_id = comp.id
JOIN registries r ON c.registry_id = r.id
JOIN courses cr ON r.course_id = cr.id
WHERE c.coursedateend IS NOT NULL
  AND (c.coursedateend + cr.expirytime::int * 365) >= CURRENT_DATE
  AND (c.coursedateend + cr.expirytime::int * 365) < CURRENT_DATE + INTERVAL '30 days'
  AND c.deleted_at IS NULL
ORDER BY expiry_date ASC
LIMIT 50
`

type ListExpiringCertificatesRow struct {
	ID           int64  `json:"id"`
	ExpiryDate   string `json:"expiry_date"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	CompanyName  string `json:"company_name"`
	Year         int64  `json:"year"`
	Number       int32  `json:"number"`
	CourseName   string `json:"course_name"`
	CourseSymbol string `json:"course_symbol"`
}

func (q *Queries) ListExpiringCertificates(ctx context.Context) ([]ListExpiringCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listExpiringCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringCertificatesRow{}
	for rows.Next() {
		var i ListExpiringCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiryDate,
			&i.Firstname,
			&i.Lastname,
			&i.CompanyName,
			&i.Year,
			&i.Number,
			&i.CourseName,
			&i.CourseSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
