// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
)

const countExpiringCertificates = `-- name: CountExpiringCertificates :one
SELECT COUNT(*)
FROM certificates c
WHERE c.deleted_at IS NULL
  AND (
      CASE
          WHEN c.coursedateend IS NOT NULL AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
          THEN c.coursedateend + c.course_expiry_time_snapshot::int * 365
      END
  ) >= CURRENT_DATE
  AND (
      CASE
          WHEN c.coursedateend IS NOT NULL AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
          THEN c.coursedateend + c.course_expiry_time_snapshot::int * 365
      END
  ) < CURRENT_DATE + 30
`

// Ten sam zbiór co ListExpiringCertificates, bez limitu. Wcześniej licznik i lista
// różniły się warunkami (lista pomijała kursantów bez firmy).
func (q *Queries) CountExpiringCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringCertificates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM students) AS total_students,
    (SELECT COUNT(*) FROM companies) AS total_companies,
    (SELECT COUNT(*) FROM certificates WHERE deleted_at IS NULL) AS total_certificates
`

type GetDashboardStatsRow struct {
	TotalStudents     int64 `json:"total_students"`
	TotalCompanies    int64 `json:"total_companies"`
	TotalCertificates int64 `json:"total_certificates"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalStudents, &i.TotalCompanies, &i.TotalCertificates)
	return i, err
}

const listExpiringCertificates = `-- name: ListExpiringCertificates :many
WITH expiring AS (
    SELECT
        c.id,
        CASE
            WHEN c.coursedateend IS NOT NULL AND c.course_expiry_time_snapshot ~ '^[0-9]+$'
            THEN c.coursedateend + c.course_expiry_time_snapshot::int * 365
        END AS expiry,
        c.student_firstname_snapshot,
        c.student_lastname_snapshot,
        c.company_name_snapshot,
        c.course_name_snapshot,
        c.course_symbol_snapshot,
        c.registry_id
    FROM certificates c
    WHERE c.deleted_at IS NULL
)
SELECT
    e.id,
    TO_CHAR(e.expiry, 'YYYY-MM-DD') AS expiry_date,
    e.student_firstname_snapshot AS firstname,
    e.student_lastname_snapshot AS lastname,
    COALESCE(e.company_name_snapshot, '') AS company_name,
    r.year,
    r.number,
    e.course_name_snapshot AS course_name,
    e.course_symbol_snapshot AS course_symbol
FROM expiring e
JOIN registries r ON r.id = e.registry_id
WHERE e.expiry >= CURRENT_DATE
  AND e.expiry < CURRENT_DATE + 30
ORDER BY e.expiry ASC, e.id ASC
LIMIT 50
`

type ListExpiringCertificatesRow struct {
	ID           int64  `json:"id"`
	ExpiryDate   string `json:"expiry_date"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	CompanyName  string `json:"company_name"`
	Year         int64  `json:"year"`
	Number       int32  `json:"number"`
	CourseName   string `json:"course_name"`
	CourseSymbol string `json:"course_symbol"`
}

// Ważność liczona tak samo jak expiry_date w ListCertificates: z okresu ważności
// zapisanego w zaświadczeniu w chwili wystawienia, a nie z aktualnego okresu kursu.
// Dane kursanta, firmy i kursu też pochodzą z kopii w zaświadczeniu, więc zaświadczenie
// kursanta bez firmy jest na liście (z pustą nazwą firmy), tak jak w ogólnej liście.
// CASE gwarantuje, że rzutowanie na int nie wykona się dla nieliczbowego okresu.
func (q *Queries) ListExpiringCertificates(ctx context.Context) ([]ListExpiringCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listExpiringCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringCertificatesRow{}
	for rows.Next() {
		var i ListExpiringCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiryDate,
			&i.Firstname,
			&i.Lastname,
			&i.CompanyName,
			&i.Year,
			&i.Number,
			&i.CourseName,
			&i.CourseSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
