// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireIdempotencyKeyLock = `-- name: AcquireIdempotencyKeyLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('idempotency:' || $1::text, 0))
`

// Szeregowanie równoległych ponowień z tym samym kluczem: druga transakcja czeka,
// aż pierwsza zatwierdzi zaświadczenie, i dopiero wtedy sprawdza klucz.
func (q *Queries) AcquireIdempotencyKeyLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, acquireIdempotencyKeyLock, key)
	return err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
WITH stored AS (
    INSERT INTO idempotency_keys (key, request_hash, certificate_id)
    VALUES ($1::text, $2::text, $3::bigint)
    RETURNING key, certificate_id
)
UPDATE certificates
SET idempotency_key = stored.key
FROM stored
WHERE certificates.id = stored.certificate_id
`

type CreateIdempotencyKeyParams struct {
	Key           string `json:"key"`
	RequestHash   string `json:"request_hash"`
	CertificateID int64  `json:"certificate_id"`
}

// Klucz trafia też na zaświadczenie (certificates.idempotency_key), bo wpis w tej tabeli
// jest usuwany po 30 dniach, a zdarzenia webhooka o dokumencie mogą przyjść później.
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, createIdempotencyKey, arg.Key, arg.RequestHash, arg.CertificateID)
	return err
}

const deleteIdempotencyKeysOlderThan = `-- name: DeleteIdempotencyKeysOlderThan :execrows
DELETE FROM idempotency_keys
WHERE created_at < $1::timestamptz
`

func (q *Queries) DeleteIdempotencyKeysOlderThan(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdempotencyKeysOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT
    ik.request_hash,
    ik.certificate_id,
    r.year AS registry_year,
    r.number AS registry_number,
    c.verification_code
FROM idempotency_keys ik
JOIN certificates c ON c.id = ik.certificate_id
JOIN registries r ON r.id = c.registry_id
WHERE ik.key = $1
`

type GetIdempotencyKeyRow struct {
	RequestHash      string `json:"request_hash"`
	CertificateID    int64  `json:"certificate_id"`
	RegistryYear     int64  `json:"registry_year"`
	RegistryNumber   int32  `json:"registry_number"`
	VerificationCode string `json:"verification_code"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.CertificateID,
		&i.RegistryYear,
		&i.RegistryNumber,
		&i.VerificationCode,
	)
	return i, err
}
