// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addJournalAttendee = `-- name: AddJournalAttendee :one
  WITH journal_header AS (
      SELECT
          j.id,
          comp.name AS company_name
      FROM training_journals j
      LEFT JOIN companies comp ON comp.id = j.company_id
      WHERE j.id = $1
  ),
  student_data AS (
      SELECT
          s.id,
          TRIM(CONCAT_WS(' ', s.lastname, s.firstname, COALESCE(s.secondname, ''))) AS full_name_snapshot,
          s.birthdate AS birthdate_snapshot,
          COALESCE(c.name, jh.company_name) AS company_name_snapshot
      FROM students s
      CROSS JOIN journal_header jh
      LEFT JOIN companies c ON c.id = s.company_id
      WHERE s.id = $2
  ),
  next_sort_order AS (
      SELECT
          COALESCE(MAX(a.sort_order), 0) + 1 AS value
      FROM training_journal_attendees a
      WHERE a.journal_id = $1
  ),
  inserted AS (
      INSERT INTO training_journal_attendees (
          journal_id,
          student_id,
          full_name_snapshot,
          birthdate_snapshot,
          company_name_snapshot,
          sort_order
      )
      SELECT
          $1,
          $2,
          sd.full_name_snapshot,
          sd.birthdate_snapshot,
          sd.company_name_snapshot,
          nso.value
      FROM student_data sd
      CROSS JOIN next_sort_order nso
      RETURNING
          id,
          journal_id,
          student_id,
          certificate_id,
          full_name_snapshot,
          birthdate_snapshot,
          company_name_snapshot,
          sort_order,
          created_at
  )
  SELECT
      i.id,
      i.journal_id,
      i.student_id,
      i.certificate_id,
      i.full_name_snapshot,
      i.birthdate_snapshot,
      i.company_name_snapshot,
      i.sort_order,
      i.created_at,
      c.date AS certificate_date,
      r.year AS certificate_registry_year,
      COALESCE(r.number::bigint, 0::bigint) AS certificate_registry_number,
      cr.symbol AS certificate_course_symbol
  FROM inserted i
  LEFT JOIN certificates c ON c.id = i.certificate_id
  LEFT JOIN registries r ON r.id = c.registry_id
  LEFT JOIN courses cr ON cr.id = r.course_id
`

type AddJournalAttendeeParams struct {
	JournalID int64 `json:"journal_id"`
	StudentID int64 `json:"student_id"`
}

type AddJournalAttendeeRow struct {
	ID                        int64              `json:"id"`
	JournalID                 int64              `json:"journal_id"`
	StudentID                 int64              `json:"student_id"`
	CertificateID             pgtype.Int8        `json:"certificate_id"`
	FullNameSnapshot          string             `json:"full_name_snapshot"`
	BirthdateSnapshot         pgtype.Date        `json:"birthdate_snapshot"`
	CompanyNameSnapshot       pgtype.Text        `json:"company_name_snapshot"`
	SortOrder                 int32              `json:"sort_order"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CertificateDate           pgtype.Date        `json:"certificate_date"`
	CertificateRegistryYear   pgtype.Int8        `json:"certificate_registry_year"`
	CertificateRegistryNumber interface{}        `json:"certificate_registry_number"`
	CertificateCourseSymbol   pgtype.Text        `json:"certificate_course_symbol"`
}

func (q *Queries) AddJournalAttendee(ctx context.Context, arg AddJournalAttendeeParams) (AddJournalAttendeeRow, error) {
	row := q.db.QueryRow(ctx, addJournalAttendee, arg.JournalID, arg.StudentID)
	var i AddJournalAttendeeRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.StudentID,
		&i.CertificateID,
		&i.FullNameSnapshot,
		&i.BirthdateSnapshot,
		&i.CompanyNameSnapshot,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CertificateDate,
		&i.CertificateRegistryYear,
		&i.CertificateRegistryNumber,
		&i.CertificateCourseSymbol,
	)
	return i, err
}

const closeJournal = `-- name: CloseJournal :execrows
  UPDATE training_journals
  SET
      status = 'closed',
      closed_at = COALESCE(closed_at, now()),
      updated_at = now()
  WHERE id = $1
    AND status <> 'closed'
`

func (q *Queries) CloseJournal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, closeJournal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createJournal = `-- name: CreateJournal :one
  WITH selected_course AS (
      SELECT
          c.id,
          c.symbol,
          COALESCE(c.courseprogram::jsonb, '[]'::jsonb) AS courseprogram,
          COALESCE(
              (
                  SELECT SUM(
                      COALESCE(NULLIF(entry->>'TheoryTime', '')::numeric, 0)
                      + COALESCE(NULLIF(entry->>'PracticeTime', '')::numeric, 0)
                  )
                  FROM jsonb_array_elements(COALESCE(c.courseprogram::jsonb, '[]'::jsonb)) entry
              ),
              0::numeric
          ) AS total_hours
      FROM courses c
      WHERE c.id = $1
  ),
  inserted AS (
      INSERT INTO training_journals (
          course_id,
          company_id,
          title,
          course_symbol,
          organizer_name,
          organizer_address,
          location,
          form_of_training,
          legal_basis,
          date_start,
          date_end,
          total_hours,
          notes,
          created_by_user_id
      )
      SELECT
          $1,
          $2,
          $3,
          sc.symbol,
          $4,
          $5,
          $6,
          $7,
          $8,
          $9,
          $10,
          sc.total_hours,
          $11,
          $12
      FROM selected_course sc
      RETURNING
          id,
          course_id,
          company_id,
          title,
          course_symbol,
          organizer_name,
          organizer_address,
          location,
          form_of_training,
          legal_basis,
          date_start,
          date_end,
          total_hours,
          notes,
          status,
          created_by_user_id,
          created_at,
          updated_at,
          closed_at
  ),
  inserted_sessions AS (
      INSERT INTO training_journal_sessions (
          journal_id,
          session_date,
          hours,
          topic,
          trainer_name,
          sort_order
      )
      SELECT
          i.id,
          i.date_start,
          COALESCE(NULLIF(entry.item->>'TheoryTime', '')::numeric, 0)
              + COALESCE(NULLIF(entry.item->>'PracticeTime', '')::numeric, 0),
          COALESCE(NULLIF(TRIM(entry.item->>'Subject'), ''), 'Temat ' || entry.ordinality::text),
          i.organizer_name,
          entry.ordinality::integer
      FROM inserted i
      CROSS JOIN selected_course sc
      CROSS JOIN LATERAL jsonb_array_elements(COALESCE(sc.courseprogram::jsonb, '[]'::jsonb))
          WITH ORDINALITY AS entry(item, ordinality)
      WHERE
          TRIM(COALESCE(entry.item->>'Subject', '')) <> ''
          OR COALESCE(NULLIF(entry.item->>'TheoryTime', '')::numeric, 0) > 0
          OR COALESCE(NULLIF(entry.item->>'PracticeTime', '')::numeric, 0) > 0
  )
  SELECT
      i.id,
      i.course_id,
      c.name AS course_name,
      i.company_id,
      comp.name AS company_name,
      i.title,
      i.course_symbol,
      i.organizer_name,
      i.organizer_address,
      i.location,
      i.form_of_training,
      i.legal_basis,
      i.date_start,
      i.date_end,
      i.total_hours,
      i.notes,
      i.status,
      i.created_by_user_id,
      i.created_at,
      i.updated_at,
      i.closed_at,
      0::bigint AS attendees_count,
      0::bigint AS sessions_count
  FROM inserted i
  JOIN courses c ON c.id = i.course_id
  LEFT JOIN companies comp ON comp.id = i.company_id
`

type CreateJournalParams struct {
	CourseID         int64       `json:"course_id"`
	CompanyID        pgtype.Int8 `json:"company_id"`
	Title            string      `json:"title"`
	OrganizerName    string      `json:"organizer_name"`
	OrganizerAddress pgtype.Text `json:"organizer_address"`
	Location         string      `json:"location"`
	FormOfTraining   string      `json:"form_of_training"`
	LegalBasis       string      `json:"legal_basis"`
	DateStart        pgtype.Date `json:"date_start"`
	DateEnd          pgtype.Date `json:"date_end"`
	Notes            pgtype.Text `json:"notes"`
	CreatedByUserID  int64       `json:"created_by_user_id"`
}

type CreateJournalRow struct {
	ID               int64              `json:"id"`
	CourseID         int64              `json:"course_id"`
	CourseName       string             `json:"course_name"`
	CompanyID        pgtype.Int8        `json:"company_id"`
	CompanyName      pgtype.Text        `json:"company_name"`
	Title            string             `json:"title"`
	CourseSymbol     string             `json:"course_symbol"`
	OrganizerName    string             `json:"organizer_name"`
	OrganizerAddress pgtype.Text        `json:"organizer_address"`
	Location         string             `json:"location"`
	FormOfTraining   string             `json:"form_of_training"`
	LegalBasis       string             `json:"legal_basis"`
	DateStart        pgtype.Date        `json:"date_start"`
	DateEnd          pgtype.Date        `json:"date_end"`
	TotalHours       pgtype.Numeric     `json:"total_hours"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	CreatedByUserID  int64              `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	AttendeesCount   int64              `json:"attendees_count"`
	SessionsCount    int64              `json:"sessions_count"`
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (CreateJournalRow, error) {
	row := q.db.QueryRow(ctx, createJournal,
		arg.CourseID,
		arg.CompanyID,
		arg.Title,
		arg.OrganizerName,
		arg.OrganizerAddress,
		arg.Location,
		arg.FormOfTraining,
		arg.LegalBasis,
		arg.DateStart,
		arg.DateEnd,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i CreateJournalRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CourseName,
		&i.CompanyID,
		&i.CompanyName,
		&i.Title,
		&i.CourseSymbol,
		&i.OrganizerName,
		&i.OrganizerAddress,
		&i.Location,
		&i.FormOfTraining,
		&i.LegalBasis,
		&i.DateStart,
		&i.DateEnd,
		&i.TotalHours,
		&i.Notes,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.AttendeesCount,
		&i.SessionsCount,
	)
	return i, err
}

const deleteJournal = `-- name: DeleteJournal :execrows
  DELETE FROM training_journals
  WHERE id = $1
`

func (q *Queries) DeleteJournal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJournal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJournalAttendanceScan = `-- name: DeleteJournalAttendanceScan :execrows
  DELETE FROM training_journal_attendance_scans
  WHERE journal_id = $1
`

func (q *Queries) DeleteJournalAttendanceScan(ctx context.Context, journalID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJournalAttendanceScan, journalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteJournalAttendee = `-- name: DeleteJournalAttendee :execrows
  DELETE FROM training_journal_attendees
  WHERE journal_id = $1
    AND id = $2
`

type DeleteJournalAttendeeParams struct {
	JournalID int64 `json:"journal_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) DeleteJournalAttendee(ctx context.Context, arg DeleteJournalAttendeeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJournalAttendee, arg.JournalID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const generateJournalSessionsFromCourse = `-- name: GenerateJournalSessionsFromCourse :execrows
  WITH journal_source AS (
      SELECT
          j.id,
          j.date_start,
          j.organizer_name,
          COALESCE(c.courseprogram::jsonb, '[]'::jsonb) AS course_program
      FROM training_journals j
      JOIN courses c ON c.id = j.course_id
      WHERE j.id = $1
  ),
  program_entries AS (
      SELECT
          js.id AS journal_id,
          js.date_start AS session_date,
          js.organizer_name AS trainer_name,
          TRIM(COALESCE(entry.item->>'Subject', '')) AS topic,
          COALESCE(NULLIF(entry.item->>'TheoryTime', '')::numeric, 0)
              + COALESCE(NULLIF(entry.item->>'PracticeTime', '')::numeric, 0) AS hours,
          entry.ordinality::integer AS sort_order
      FROM journal_source js
      CROSS JOIN LATERAL jsonb_array_elements(js.course_program)
          WITH ORDINALITY AS entry(item, ordinality)
  ),
  filtered_entries AS (
      SELECT
          journal_id,
          session_date,
          trainer_name,
          COALESCE(NULLIF(topic, ''), 'Temat ' || sort_order::text) AS topic,
          hours,
          sort_order
      FROM program_entries
      WHERE topic <> '' OR hours > 0
  )
  INSERT INTO training_journal_sessions (
      journal_id,
      session_date,
      hours,
      topic,
      trainer_name,
      sort_order
  )
  SELECT
      fe.journal_id,
      fe.session_date,
      fe.hours,
      fe.topic,
      fe.trainer_name,
      fe.sort_order
  FROM filtered_entries fe
  WHERE NOT EXISTS (
      SELECT 1
      FROM training_journal_sessions existing
      WHERE existing.journal_id = fe.journal_id
  )
`

func (q *Queries) GenerateJournalSessionsFromCourse(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, generateJournalSessionsFromCourse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJournalAttendanceScanFile = `-- name: GetJournalAttendanceScanFile :one
  SELECT
      id,
      journal_id,
      file_name,
      content_type,
      file_data
  FROM training_journal_attendance_scans
  WHERE journal_id = $1
`

type GetJournalAttendanceScanFileRow struct {
	ID          int64  `json:"id"`
	JournalID   int64  `json:"journal_id"`
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	FileData    []byte `json:"file_data"`
}

func (q *Queries) GetJournalAttendanceScanFile(ctx context.Context, journalID int64) (GetJournalAttendanceScanFileRow, error) {
	row := q.db.QueryRow(ctx, getJournalAttendanceScanFile, journalID)
	var i GetJournalAttendanceScanFileRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.FileName,
		&i.ContentType,
		&i.FileData,
	)
	return i, err
}

const getJournalAttendanceScanMeta = `-- name: GetJournalAttendanceScanMeta :one
  SELECT
      id,
      journal_id,
      file_name,
      content_type,
      file_size,
      uploaded_by_user_id,
      created_at,
      updated_at
  FROM training_journal_attendance_scans
  WHERE journal_id = $1
`

type GetJournalAttendanceScanMetaRow struct {
	ID               int64              `json:"id"`
	JournalID        int64              `json:"journal_id"`
	FileName         string             `json:"file_name"`
	ContentType      string             `json:"content_type"`
	FileSize         int64              `json:"file_size"`
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetJournalAttendanceScanMeta(ctx context.Context, journalID int64) (GetJournalAttendanceScanMetaRow, error) {
	row := q.db.QueryRow(ctx, getJournalAttendanceScanMeta, journalID)
	var i GetJournalAttendanceScanMetaRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.FileName,
		&i.ContentType,
		&i.FileSize,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalAttendeeForCertificateGeneration = `-- name: GetJournalAttendeeForCertificateGeneration :one
  SELECT
      a.id AS attendee_id,
      a.journal_id,
      a.student_id,
      a.certificate_id,
      j.course_id,
      j.date_start,
      j.date_end
  FROM training_journal_attendees a
  JOIN training_journals j ON j.id = a.journal_id
  WHERE a.journal_id = $1
    AND a.id = $2
`

type GetJournalAttendeeForCertificateGenerationParams struct {
	JournalID int64 `json:"journal_id"`
	ID        int64 `json:"id"`
}

type GetJournalAttendeeForCertificateGenerationRow struct {
	AttendeeID    int64       `json:"attendee_id"`
	JournalID     int64       `json:"journal_id"`
	StudentID     int64       `json:"student_id"`
	CertificateID pgtype.Int8 `json:"certificate_id"`
	CourseID      int64       `json:"course_id"`
	DateStart     pgtype.Date `json:"date_start"`
	DateEnd       pgtype.Date `json:"date_end"`
}

func (q *Queries) GetJournalAttendeeForCertificateGeneration(ctx context.Context, arg GetJournalAttendeeForCertificateGenerationParams) (GetJournalAttendeeForCertificateGenerationRow, error) {
	row := q.db.QueryRow(ctx, getJournalAttendeeForCertificateGeneration, arg.JournalID, arg.ID)
	var i GetJournalAttendeeForCertificateGenerationRow
	err := row.Scan(
		&i.AttendeeID,
		&i.JournalID,
		&i.StudentID,
		&i.CertificateID,
		&i.CourseID,
		&i.DateStart,
		&i.DateEnd,
	)
	return i, err
}

const getJournalByID = `-- name: GetJournalByID :one
  SELECT
      j.id,
      j.course_id,
      c.name AS course_name,
      j.company_id,
      comp.name AS company_name,
      j.title,
      j.course_symbol,
      j.organizer_name,
      j.organizer_address,
      j.location,
      j.form_of_training,
      j.legal_basis,
      j.date_start,
      j.date_end,
      j.total_hours,
      j.notes,
      j.status,
      j.created_by_user_id,
      j.created_at,
      j.updated_at,
      j.closed_at,
      (
          SELECT COUNT(*)::bigint
          FROM training_journal_attendees a
          WHERE a.journal_id = j.id
      ) AS attendees_count,
      (
          SELECT COUNT(*)::bigint
          FROM training_journal_sessions s
          WHERE s.journal_id = j.id
      ) AS sessions_count
  FROM training_journals j
  JOIN courses c ON c.id = j.course_id
  LEFT JOIN companies comp ON comp.id = j.company_id
  WHERE j.id = $1
`

type GetJournalByIDRow struct {
	ID               int64              `json:"id"`
	CourseID         int64              `json:"course_id"`
	CourseName       string             `json:"course_name"`
	CompanyID        pgtype.Int8        `json:"company_id"`
	CompanyName      pgtype.Text        `json:"company_name"`
	Title            string             `json:"title"`
	CourseSymbol     string             `json:"course_symbol"`
	OrganizerName    string             `json:"organizer_name"`
	OrganizerAddress pgtype.Text        `json:"organizer_address"`
	Location         string             `json:"location"`
	FormOfTraining   string             `json:"form_of_training"`
	LegalBasis       string             `json:"legal_basis"`
	DateStart        pgtype.Date        `json:"date_start"`
	DateEnd          pgtype.Date        `json:"date_end"`
	TotalHours       pgtype.Numeric     `json:"total_hours"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	CreatedByUserID  int64              `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	AttendeesCount   int64              `json:"attendees_count"`
	SessionsCount    int64              `json:"sessions_count"`
}

func (q *Queries) GetJournalByID(ctx context.Context, id int64) (GetJournalByIDRow, error) {
	row := q.db.QueryRow(ctx, getJournalByID, id)
	var i GetJournalByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CourseName,
		&i.CompanyID,
		&i.CompanyName,
		&i.Title,
		&i.CourseSymbol,
		&i.OrganizerName,
		&i.OrganizerAddress,
		&i.Location,
		&i.FormOfTraining,
		&i.LegalBasis,
		&i.DateStart,
		&i.DateEnd,
		&i.TotalHours,
		&i.Notes,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.AttendeesCount,
		&i.SessionsCount,
	)
	return i, err
}

const listJournalAttendance = `-- name: ListJournalAttendance :many
  SELECT
      a.id,
      a.journal_session_id,
      a.journal_attendee_id,
      a.present,
      a.created_at,
      a.updated_at
  FROM training_journal_attendance a
  JOIN training_journal_sessions s ON s.id = a.journal_session_id
  WHERE s.journal_id = $1
  ORDER BY a.journal_session_id, a.journal_attendee_id
`

func (q *Queries) ListJournalAttendance(ctx context.Context, journalID int64) ([]TrainingJournalAttendance, error) {
	rows, err := q.db.Query(ctx, listJournalAttendance, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingJournalAttendance{}
	for rows.Next() {
		var i TrainingJournalAttendance
		if err := rows.Scan(
			&i.ID,
			&i.JournalSessionID,
			&i.JournalAttendeeID,
			&i.Present,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalAttendees = `-- name: ListJournalAttendees :many
  SELECT
      a.id,
      a.journal_id,
      a.student_id,
      a.certificate_id,
      a.full_name_snapshot,
      a.birthdate_snapshot,
      a.company_name_snapshot,
      a.sort_order,
      a.created_at,
      c.date AS certificate_date,
      r.year AS certificate_registry_year,
      COALESCE(r.number::bigint, 0::bigint) AS certificate_registry_number,
      cr.symbol AS certificate_course_symbol
  FROM training_journal_attendees a
  LEFT JOIN certificates c ON c.id = a.certificate_id
  LEFT JOIN registries r ON r.id = c.registry_id
  LEFT JOIN courses cr ON cr.id = r.course_id
  WHERE a.journal_id = $1
  ORDER BY a.sort_order, a.id
`

type ListJournalAttendeesRow struct {
	ID                        int64              `json:"id"`
	JournalID                 int64              `json:"journal_id"`
	StudentID                 int64              `json:"student_id"`
	CertificateID             pgtype.Int8        `json:"certificate_id"`
	FullNameSnapshot          string             `json:"full_name_snapshot"`
	BirthdateSnapshot         pgtype.Date        `json:"birthdate_snapshot"`
	CompanyNameSnapshot       pgtype.Text        `json:"company_name_snapshot"`
	SortOrder                 int32              `json:"sort_order"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CertificateDate           pgtype.Date        `json:"certificate_date"`
	CertificateRegistryYear   pgtype.Int8        `json:"certificate_registry_year"`
	CertificateRegistryNumber interface{}        `json:"certificate_registry_number"`
	CertificateCourseSymbol   pgtype.Text        `json:"certificate_course_symbol"`
}

func (q *Queries) ListJournalAttendees(ctx context.Context, journalID int64) ([]ListJournalAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listJournalAttendees, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalAttendeesRow{}
	for rows.Next() {
		var i ListJournalAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.StudentID,
			&i.CertificateID,
			&i.FullNameSnapshot,
			&i.BirthdateSnapshot,
			&i.CompanyNameSnapshot,
			&i.SortOrder,
			&i.CreatedAt,
			&i.CertificateDate,
			&i.CertificateRegistryYear,
			&i.CertificateRegistryNumber,
			&i.CertificateCourseSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalSessions = `-- name: ListJournalSessions :many
  SELECT
      s.id,
      s.journal_id,
      s.session_date,
      s.start_time,
      s.end_time,
      s.hours,
      s.topic,
      s.trainer_name,
      s.sort_order,
      s.created_at
  FROM training_journal_sessions s
  WHERE s.journal_id = $1
  ORDER BY s.sort_order, s.id
`

func (q *Queries) ListJournalSessions(ctx context.Context, journalID int64) ([]TrainingJournalSession, error) {
	rows, err := q.db.Query(ctx, listJournalSessions, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingJournalSession{}
	for rows.Next() {
		var i TrainingJournalSession
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.SessionDate,
			&i.StartTime,
			&i.EndTime,
			&i.Hours,
			&i.Topic,
			&i.TrainerName,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournals = `-- name: ListJournals :many
  SELECT
      j.id,
      j.title,
      j.course_symbol,
      j.organizer_name,
      j.location,
      j.form_of_training,
      j.date_start,
      j.date_end,
      j.total_hours,
      j.status,
      j.created_at,
      c.id AS course_id,
      c.name AS course_name,
      comp.id AS company_id,
      comp.name AS company_name,
      (
          SELECT COUNT(*)::bigint
          FROM training_journal_attendees a
          WHERE a.journal_id = j.id
      ) AS attendees_count,
      (
          SELECT COUNT(*)::bigint
          FROM training_journal_sessions s
          WHERE s.journal_id = j.id
      ) AS sessions_count
  FROM training_journals j
  JOIN courses c ON c.id = j.course_id
  LEFT JOIN companies comp ON comp.id = j.company_id
  WHERE
      (
          $1::text IS NULL
          OR COALESCE(j.title, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(j.course_symbol, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(c.name, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(comp.name, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(j.location, '') ILIKE '%' || $1::text || '%'
          OR COALESCE(j.organizer_name, '') ILIKE '%' || $1::text || '%'
      )
      AND (
          $2::bigint IS NULL
          OR j.course_id = $2::bigint
      )
      AND (
          $3::bigint IS NULL
          OR j.company_id = $3::bigint
      )
      AND (
          $4::text IS NULL
          OR j.status = $4::text
      )
      AND (
          $5::date IS NULL
          OR j.date_start >= $5::date
      )
      AND (
          $6::date IS NULL
          OR j.date_end <= $6::date
      )
  ORDER BY j.date_start DESC, j.id DESC
  LIMIT $7
`

type ListJournalsParams struct {
	Search     pgtype.Text `json:"search"`
	CourseID   pgtype.Int8 `json:"course_id"`
	CompanyID  pgtype.Int8 `json:"company_id"`
	Status     pgtype.Text `json:"status"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
	LimitCount int32       `json:"limit_count"`
}

type ListJournalsRow struct {
	ID             int64              `json:"id"`
	Title          string             `json:"title"`
	CourseSymbol   string             `json:"course_symbol"`
	OrganizerName  string             `json:"organizer_name"`
	Location       string             `json:"location"`
	FormOfTraining string             `json:"form_of_training"`
	DateStart      pgtype.Date        `json:"date_start"`
	DateEnd        pgtype.Date        `json:"date_end"`
	TotalHours     pgtype.Numeric     `json:"total_hours"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CourseID       int64              `json:"course_id"`
	CourseName     string             `json:"course_name"`
	CompanyID      pgtype.Int8        `json:"company_id"`
	CompanyName    pgtype.Text        `json:"company_name"`
	AttendeesCount int64              `json:"attendees_count"`
	SessionsCount  int64              `json:"sessions_count"`
}

func (q *Queries) ListJournals(ctx context.Context, arg ListJournalsParams) ([]ListJournalsRow, error) {
	rows, err := q.db.Query(ctx, listJournals,
		arg.Search,
		arg.CourseID,
		arg.CompanyID,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalsRow{}
	for rows.Next() {
		var i ListJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CourseSymbol,
			&i.OrganizerName,
			&i.Location,
			&i.FormOfTraining,
			&i.DateStart,
			&i.DateEnd,
			&i.TotalHours,
			&i.Status,
			&i.CreatedAt,
			&i.CourseID,
			&i.CourseName,
			&i.CompanyID,
			&i.CompanyName,
			&i.AttendeesCount,
			&i.SessionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalAttendeeCertificate = `-- name: UpdateJournalAttendeeCertificate :one
  WITH attendee_source AS (
      SELECT
          a.id,
          a.journal_id,
          a.student_id
      FROM training_journal_attendees a
      WHERE a.journal_id = $1
        AND a.id = $2
  ),
  valid_certificate AS (
      SELECT c.id
      FROM attendee_source src
      JOIN training_journals j ON j.id = src.journal_id
      JOIN certificates c ON c.id = $3::bigint
          AND c.student_id = src.student_id
          AND c.deleted_at IS NULL
      JOIN registries r ON r.id = c.registry_id
      WHERE r.course_id = j.course_id
  ),
  updated AS (
      UPDATE training_journal_attendees a
      SET certificate_id = CASE
          WHEN $3::bigint IS NULL THEN NULL
          ELSE (SELECT vc.id FROM valid_certificate vc)
      END
      FROM attendee_source src
      WHERE a.id = src.id
        AND a.journal_id = src.journal_id
        AND (
            $3::bigint IS NULL
            OR EXISTS (SELECT 1 FROM valid_certificate)
        )
      RETURNING
          a.id,
          a.journal_id,
          a.student_id,
          a.certificate_id,
          a.full_name_snapshot,
          a.birthdate_snapshot,
          a.company_name_snapshot,
          a.sort_order,
          a.created_at
  )
  SELECT
      u.id,
      u.journal_id,
      u.student_id,
      u.certificate_id,
      u.full_name_snapshot,
      u.birthdate_snapshot,
      u.company_name_snapshot,
      u.sort_order,
      u.created_at,
      c.date AS certificate_date,
      r.year AS certificate_registry_year,
      COALESCE(r.number::bigint, 0::bigint) AS certificate_registry_number,
      cr.symbol AS certificate_course_symbol
  FROM updated u
  LEFT JOIN certificates c ON c.id = u.certificate_id
  LEFT JOIN registries r ON r.id = c.registry_id
  LEFT JOIN courses cr ON cr.id = r.course_id
`

type UpdateJournalAttendeeCertificateParams struct {
	JournalID     int64       `json:"journal_id"`
	AttendeeID    int64       `json:"attendee_id"`
	CertificateID pgtype.Int8 `json:"certificate_id"`
}

type UpdateJournalAttendeeCertificateRow struct {
	ID                        int64              `json:"id"`
	JournalID                 int64              `json:"journal_id"`
	StudentID                 int64              `json:"student_id"`
	CertificateID             pgtype.Int8        `json:"certificate_id"`
	FullNameSnapshot          string             `json:"full_name_snapshot"`
	BirthdateSnapshot         pgtype.Date        `json:"birthdate_snapshot"`
	CompanyNameSnapshot       pgtype.Text        `json:"company_name_snapshot"`
	SortOrder                 int32              `json:"sort_order"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	CertificateDate           pgtype.Date        `json:"certificate_date"`
	CertificateRegistryYear   pgtype.Int8        `json:"certificate_registry_year"`
	CertificateRegistryNumber interface{}        `json:"certificate_registry_number"`
	CertificateCourseSymbol   pgtype.Text        `json:"certificate_course_symbol"`
}

func (q *Queries) UpdateJournalAttendeeCertificate(ctx context.Context, arg UpdateJournalAttendeeCertificateParams) (UpdateJournalAttendeeCertificateRow, error) {
	row := q.db.QueryRow(ctx, updateJournalAttendeeCertificate, arg.JournalID, arg.AttendeeID, arg.CertificateID)
	var i UpdateJournalAttendeeCertificateRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.StudentID,
		&i.CertificateID,
		&i.FullNameSnapshot,
		&i.BirthdateSnapshot,
		&i.CompanyNameSnapshot,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CertificateDate,
		&i.CertificateRegistryYear,
		&i.CertificateRegistryNumber,
		&i.CertificateCourseSymbol,
	)
	return i, err
}

const updateJournalHeader = `-- name: UpdateJournalHeader :one
  WITH updated AS (
      UPDATE training_journals AS tj
      SET
          company_id = $1,
          title = $2,
          organizer_name = $3,
          organizer_address = $4,
          location = $5,
          form_of_training = $6,
          legal_basis = $7,
          date_start = $8,
          date_end = $9,
          notes = $10,
          updated_at = now()
      WHERE tj.id = $11
      RETURNING
          tj.id,
          tj.course_id,
          tj.company_id,
          tj.title,
          tj.course_symbol,
          tj.organizer_name,
          tj.organizer_address,
          tj.location,
          tj.form_of_training,
          tj.legal_basis,
          tj.date_start,
          tj.date_end,
          tj.total_hours,
          tj.notes,
          tj.status,
          tj.created_by_user_id,
          tj.created_at,
          tj.updated_at,
          tj.closed_at
  )
  SELECT
      j.id,
      j.course_id,
      c.name AS course_name,
      j.company_id,
      comp.name AS company_name,
      j.title,
      j.course_symbol,
      j.organizer_name,
      j.organizer_address,
      j.location,
      j.form_of_training,
      j.legal_basis,
      j.date_start,
      j.date_end,
      j.total_hours,
      j.notes,
      j.status,
      j.created_by_user_id,
      j.created_at,
      j.updated_at,
      j.closed_at,
      (
          SELECT COUNT(*)::bigint
          FROM training_journal_attendees a
          WHERE a.journal_id = j.id
      ) AS attendees_count,
      (
          SELECT COUNT(*)::bigint
          FROM training_journal_sessions s
          WHERE s.journal_id = j.id
      ) AS sessions_count
  FROM updated j
  JOIN courses c ON c.id = j.course_id
  LEFT JOIN companies comp ON comp.id = j.company_id
`

type UpdateJournalHeaderParams struct {
	CompanyID        pgtype.Int8 `json:"company_id"`
	Title            string      `json:"title"`
	OrganizerName    string      `json:"organizer_name"`
	OrganizerAddress pgtype.Text `json:"organizer_address"`
	Location         string      `json:"location"`
	FormOfTraining   string      `json:"form_of_training"`
	LegalBasis       string      `json:"legal_basis"`
	DateStart        pgtype.Date `json:"date_start"`
	DateEnd          pgtype.Date `json:"date_end"`
	Notes            pgtype.Text `json:"notes"`
	JournalID        int64       `json:"journal_id"`
}

type UpdateJournalHeaderRow struct {
	ID               int64              `json:"id"`
	CourseID         int64              `json:"course_id"`
	CourseName       string             `json:"course_name"`
	CompanyID        pgtype.Int8        `json:"company_id"`
	CompanyName      pgtype.Text        `json:"company_name"`
	Title            string             `json:"title"`
	CourseSymbol     string             `json:"course_symbol"`
	OrganizerName    string             `json:"organizer_name"`
	OrganizerAddress pgtype.Text        `json:"organizer_address"`
	Location         string             `json:"location"`
	FormOfTraining   string             `json:"form_of_training"`
	LegalBasis       string             `json:"legal_basis"`
	DateStart        pgtype.Date        `json:"date_start"`
	DateEnd          pgtype.Date        `json:"date_end"`
	TotalHours       pgtype.Numeric     `json:"total_hours"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	CreatedByUserID  int64              `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
	AttendeesCount   int64              `json:"attendees_count"`
	SessionsCount    int64              `json:"sessions_count"`
}

func (q *Queries) UpdateJournalHeader(ctx context.Context, arg UpdateJournalHeaderParams) (UpdateJournalHeaderRow, error) {
	row := q.db.QueryRow(ctx, updateJournalHeader,
		arg.CompanyID,
		arg.Title,
		arg.OrganizerName,
		arg.OrganizerAddress,
		arg.Location,
		arg.FormOfTraining,
		arg.LegalBasis,
		arg.DateStart,
		arg.DateEnd,
		arg.Notes,
		arg.JournalID,
	)
	var i UpdateJournalHeaderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CourseName,
		&i.CompanyID,
		&i.CompanyName,
		&i.Title,
		&i.CourseSymbol,
		&i.OrganizerName,
		&i.OrganizerAddress,
		&i.Location,
		&i.FormOfTraining,
		&i.LegalBasis,
		&i.DateStart,
		&i.DateEnd,
		&i.TotalHours,
		&i.Notes,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.AttendeesCount,
		&i.SessionsCount,
	)
	return i, err
}

const updateJournalSession = `-- name: UpdateJournalSession :one
  UPDATE training_journal_sessions
  SET
      session_date = $1,
      trainer_name = $2
  WHERE journal_id = $3
    AND id = $4
  RETURNING
      id,
      journal_id,
      session_date,
      start_time,
      end_time,
      hours,
      topic,
      trainer_name,
      sort_order,
      created_at
`

type UpdateJournalSessionParams struct {
	SessionDate pgtype.Date `json:"session_date"`
	TrainerName string      `json:"trainer_name"`
	JournalID   int64       `json:"journal_id"`
	SessionID   int64       `json:"session_id"`
}

func (q *Queries) UpdateJournalSession(ctx context.Context, arg UpdateJournalSessionParams) (TrainingJournalSession, error) {
	row := q.db.QueryRow(ctx, updateJournalSession,
		arg.SessionDate,
		arg.TrainerName,
		arg.JournalID,
		arg.SessionID,
	)
	var i TrainingJournalSession
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.SessionDate,
		&i.StartTime,
		&i.EndTime,
		&i.Hours,
		&i.Topic,
		&i.TrainerName,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const upsertJournalAttendance = `-- name: UpsertJournalAttendance :one
  WITH valid_pair AS (
      SELECT
          s.id AS journal_session_id,
          a.id AS journal_attendee_id
      FROM training_journal_sessions s
      JOIN training_journal_attendees a ON a.journal_id = s.journal_id
      WHERE s.journal_id = $2
        AND s.id = $3
        AND a.id = $4
  )
  INSERT INTO training_journal_attendance (
      journal_session_id,
      journal_attendee_id,
      present
  )
  SELECT
      vp.journal_session_id,
      vp.journal_attendee_id,
      $1
  FROM valid_pair vp
  ON CONFLICT (journal_session_id, journal_attendee_id)
  DO UPDATE SET
      present = EXCLUDED.present,
      updated_at = now()
  RETURNING
      id,
      journal_session_id,
      journal_attendee_id,
      present,
      created_at,
      updated_at
`

type UpsertJournalAttendanceParams struct {
	Present           bool  `json:"present"`
	JournalID         int64 `json:"journal_id"`
	JournalSessionID  int64 `json:"journal_session_id"`
	JournalAttendeeID int64 `json:"journal_attendee_id"`
}

func (q *Queries) UpsertJournalAttendance(ctx context.Context, arg UpsertJournalAttendanceParams) (TrainingJournalAttendance, error) {
	row := q.db.QueryRow(ctx, upsertJournalAttendance,
		arg.Present,
		arg.JournalID,
		arg.JournalSessionID,
		arg.JournalAttendeeID,
	)
	var i TrainingJournalAttendance
	err := row.Scan(
		&i.ID,
		&i.JournalSessionID,
		&i.JournalAttendeeID,
		&i.Present,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJournalAttendanceScan = `-- name: UpsertJournalAttendanceScan :one
  INSERT INTO training_journal_attendance_scans (
      journal_id,
      file_name,
      content_type,
      file_size,
      file_data,
      uploaded_by_user_id
  ) VALUES (
      $1, $2, $3, $4, $5, $6
  )
  ON CONFLICT (journal_id) DO UPDATE
  SET
      file_name = EXCLUDED.file_name,
      content_type = EXCLUDED.content_type,
      file_size = EXCLUDED.file_size,
      file_data = EXCLUDED.file_data,
      uploaded_by_user_id = EXCLUDED.uploaded_by_user_id,
      updated_at = now()
  RETURNING
      id,
      journal_id,
      file_name,
      content_type,
      file_size,
      uploaded_by_user_id,
      created_at,
      updated_at
`

type UpsertJournalAttendanceScanParams struct {
	JournalID        int64  `json:"journal_id"`
	FileName         string `json:"file_name"`
	ContentType      string `json:"content_type"`
	FileSize         int64  `json:"file_size"`
	FileData         []byte `json:"file_data"`
	UploadedByUserID int64  `json:"uploaded_by_user_id"`
}

type UpsertJournalAttendanceScanRow struct {
	ID               int64              `json:"id"`
	JournalID        int64              `json:"journal_id"`
	FileName         string             `json:"file_name"`
	ContentType      string             `json:"content_type"`
	FileSize         int64              `json:"file_size"`
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertJournalAttendanceScan(ctx context.Context, arg UpsertJournalAttendanceScanParams) (UpsertJournalAttendanceScanRow, error) {
	row := q.db.QueryRow(ctx, upsertJournalAttendanceScan,
		arg.JournalID,
		arg.FileName,
		arg.ContentType,
		arg.FileSize,
		arg.FileData,
		arg.UploadedByUserID,
	)
	var i UpsertJournalAttendanceScanRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.FileName,
		&i.ContentType,
		&i.FileSize,
		&i.UploadedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
