// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legal_bases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLegalBasis = `-- name: CreateLegalBasis :one
INSERT INTO legal_bases (name, content)
VALUES ($1, $2)
RETURNING id, name, content, created_at, updated_at
`

type CreateLegalBasisParams struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (q *Queries) CreateLegalBasis(ctx context.Context, arg CreateLegalBasisParams) (LegalBasis, error) {
	row := q.db.QueryRow(ctx, createLegalBasis, arg.Name, arg.Content)
	var i LegalBasis
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLegalBasis = `-- name: DeleteLegalBasis :execrows
DELETE FROM legal_bases
WHERE id = $1
`

func (q *Queries) DeleteLegalBasis(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLegalBasis, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLegalBasisByID = `-- name: GetLegalBasisByID :one
SELECT id, name, content, created_at, updated_at
FROM legal_bases
WHERE id = $1
`

func (q *Queries) GetLegalBasisByID(ctx context.Context, id int64) (LegalBasis, error) {
	row := q.db.QueryRow(ctx, getLegalBasisByID, id)
	var i LegalBasis
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoursesByLegalBasis = `-- name: ListCoursesByLegalBasis :many
SELECT id, symbol, name
FROM courses
WHERE legal_basis_id = $1
ORDER BY symbol, id
`

type ListCoursesByLegalBasisRow struct {
	ID     int64  `json:"id"`
	Symbol string `json:"symbol"`
	Name   string `json:"name"`
}

func (q *Queries) ListCoursesByLegalBasis(ctx context.Context, legalBasisID pgtype.Int8) ([]ListCoursesByLegalBasisRow, error) {
	rows, err := q.db.Query(ctx, listCoursesByLegalBasis, legalBasisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesByLegalBasisRow{}
	for rows.Next() {
		var i ListCoursesByLegalBasisRow
		if err := rows.Scan(&i.ID, &i.Symbol, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalBases = `-- name: ListLegalBases :many
SELECT
    lb.id,
    lb.name,
    lb.content,
    lb.updated_at,
    (SELECT count(*) FROM courses c WHERE c.legal_basis_id = lb.id)::bigint AS course_count
FROM legal_bases lb
ORDER BY lower(lb.name), lb.id
`

type ListLegalBasesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Content     string             `json:"content"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CourseCount int64              `json:"course_count"`
}

// Lista do wyboru w ustawieniach kursu i w zakładce administratora. course_count mówi,
// ilu kursów dotknie zmiana treści.
func (q *Queries) ListLegalBases(ctx context.Context) ([]ListLegalBasesRow, error) {
	rows, err := q.db.Query(ctx, listLegalBases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalBasesRow{}
	for rows.Next() {
		var i ListLegalBasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.UpdatedAt,
			&i.CourseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLegalBasis = `-- name: UpdateLegalBasis :one
UPDATE legal_bases
SET name = $1,
    content = $2
WHERE id = $3
RETURNING id, name, content, created_at, updated_at
`

type UpdateLegalBasisParams struct {
	Name    string `json:"name"`
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateLegalBasis(ctx context.Context, arg UpdateLegalBasisParams) (LegalBasis, error) {
	row := q.db.QueryRow(ctx, updateLegalBasis, arg.Name, arg.Content, arg.ID)
	var i LegalBasis
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
