// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiSession struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Certificate struct {
	ID              int64              `json:"id"`
	Date            pgtype.Date        `json:"date"`
	StudentID       int32              `json:"student_id"`
	Coursedatestart pgtype.Date        `json:"coursedatestart"`
	Coursedateend   pgtype.Date        `json:"coursedateend"`
	RegistryID      int64              `json:"registry_id"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedByUserID pgtype.Int8        `json:"deleted_by_user_id"`
	DeleteReason    pgtype.Text        `json:"delete_reason"`
}

type Company struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Street        string      `json:"street"`
	City          string      `json:"city"`
	Zipcode       string      `json:"zipcode"`
	Nip           string      `json:"nip"`
	Email         pgtype.Text `json:"email"`
	Contactperson pgtype.Text `json:"contactperson"`
	Telephoneno   string      `json:"telephoneno"`
	Note          pgtype.Text `json:"note"`
}

type Course struct {
	ID            int64       `json:"id"`
	Mainname      pgtype.Text `json:"mainname"`
	Name          string      `json:"name"`
	Symbol        string      `json:"symbol"`
	Expirytime    pgtype.Text `json:"expirytime"`
	Courseprogram []byte      `json:"courseprogram"`
	Certfrontpage pgtype.Text `json:"certfrontpage"`
}

type Registry struct {
	ID       int64 `json:"id"`
	CourseID int64 `json:"course_id"`
	Year     int64 `json:"year"`
	Number   int32 `json:"number"`
}

type Student struct {
	ID            int64       `json:"id"`
	Firstname     string      `json:"firstname"`
	Lastname      string      `json:"lastname"`
	Secondname    pgtype.Text `json:"secondname"`
	Birthdate     pgtype.Date `json:"birthdate"`
	Birthplace    string      `json:"birthplace"`
	Pesel         pgtype.Text `json:"pesel"`
	Addressstreet pgtype.Text `json:"addressstreet"`
	Addresscity   pgtype.Text `json:"addresscity"`
	Telephoneno   pgtype.Text `json:"telephoneno"`
	CompanyID     pgtype.Int8 `json:"company_id"`
	Addresszip    pgtype.Text `json:"addresszip"`
}

type TrainingJournal struct {
	ID               int64              `json:"id"`
	CourseID         int64              `json:"course_id"`
	CompanyID        pgtype.Int8        `json:"company_id"`
	Title            string             `json:"title"`
	CourseSymbol     string             `json:"course_symbol"`
	OrganizerName    string             `json:"organizer_name"`
	OrganizerAddress pgtype.Text        `json:"organizer_address"`
	Location         string             `json:"location"`
	FormOfTraining   string             `json:"form_of_training"`
	LegalBasis       string             `json:"legal_basis"`
	DateStart        pgtype.Date        `json:"date_start"`
	DateEnd          pgtype.Date        `json:"date_end"`
	TotalHours       pgtype.Numeric     `json:"total_hours"`
	Notes            pgtype.Text        `json:"notes"`
	Status           string             `json:"status"`
	CreatedByUserID  int64              `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ClosedAt         pgtype.Timestamptz `json:"closed_at"`
}

type TrainingJournalAttendance struct {
	ID                int64              `json:"id"`
	JournalSessionID  int64              `json:"journal_session_id"`
	JournalAttendeeID int64              `json:"journal_attendee_id"`
	Present           bool               `json:"present"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TrainingJournalAttendanceScan struct {
	ID               int64              `json:"id"`
	JournalID        int64              `json:"journal_id"`
	FileName         string             `json:"file_name"`
	ContentType      string             `json:"content_type"`
	FileSize         int64              `json:"file_size"`
	FileData         []byte             `json:"file_data"`
	UploadedByUserID int64              `json:"uploaded_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TrainingJournalAttendee struct {
	ID                  int64              `json:"id"`
	JournalID           int64              `json:"journal_id"`
	StudentID           int64              `json:"student_id"`
	CertificateID       pgtype.Int8        `json:"certificate_id"`
	FullNameSnapshot    string             `json:"full_name_snapshot"`
	BirthdateSnapshot   pgtype.Date        `json:"birthdate_snapshot"`
	CompanyNameSnapshot pgtype.Text        `json:"company_name_snapshot"`
	SortOrder           int32              `json:"sort_order"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type TrainingJournalSession struct {
	ID          int64              `json:"id"`
	JournalID   int64              `json:"journal_id"`
	SessionDate pgtype.Date        `json:"session_date"`
	StartTime   pgtype.Time        `json:"start_time"`
	EndTime     pgtype.Time        `json:"end_time"`
	Hours       pgtype.Numeric     `json:"hours"`
	Topic       string             `json:"topic"`
	TrainerName string             `json:"trainer_name"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Password  []byte `json:"password"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Role      int32  `json:"role"`
}
