// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registries (
    course_id,
    year,
    number
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id
`

type CreateRegistryParams struct {
	CourseID int64 `json:"course_id"`
	Year     int64 `json:"year"`
	Number   int32 `json:"number"`
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRegistry, arg.CourseID, arg.Year, arg.Number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getNextRegistryNumber = `-- name: GetNextRegistryNumber :one
SELECT COALESCE(MAX(number), 0) + 1 AS next_number
FROM registries
WHERE course_id = $1 AND year = $2
`

type GetNextRegistryNumberParams struct {
	CourseID int64 `json:"course_id"`
	Year     int64 `json:"year"`
}

func (q *Queries) GetNextRegistryNumber(ctx context.Context, arg GetNextRegistryNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextRegistryNumber, arg.CourseID, arg.Year)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const listRegistryDatesForCourseYear = `-- name: ListRegistryDatesForCourseYear :many
SELECT
    c.date AS certificate_date,
    r.number AS registry_number
FROM certificates c
JOIN registries r ON r.id = c.registry_id
WHERE r.course_id = $1
  AND r.year = $2
  AND c.deleted_at IS NULL
ORDER BY r.number
`

type ListRegistryDatesForCourseYearParams struct {
	CourseID int64 `json:"course_id"`
	Year     int64 `json:"year"`
}

type ListRegistryDatesForCourseYearRow struct {
	CertificateDate pgtype.Date `json:"certificate_date"`
	RegistryNumber  int32       `json:"registry_number"`
}

func (q *Queries) ListRegistryDatesForCourseYear(ctx context.Context, arg ListRegistryDatesForCourseYearParams) ([]ListRegistryDatesForCourseYearRow, error) {
	rows, err := q.db.Query(ctx, listRegistryDatesForCourseYear, arg.CourseID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegistryDatesForCourseYearRow{}
	for rows.Next() {
		var i ListRegistryDatesForCourseYearRow
		if err := rows.Scan(&i.CertificateDate, &i.RegistryNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
