// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
  WITH inserted AS (
      INSERT INTO students (
          firstname,
          lastname,
          secondname,
          birthdate,
          birthplace,
          pesel,
          addressstreet,
          addresscity,
          addresszip,
          telephoneno,
          company_id
      ) VALUES (
          $1,
          $2,
          $3,
          $4,
          $5,
          $6,
          $7,
          $8,
          $9,
          $10,
          $11
      )
      RETURNING
          id,
          firstname,
          lastname,
          secondname,
          birthdate,
          birthplace,
          pesel,
          addressstreet,
          addresscity,
          addresszip,
          telephoneno,
          company_id
  )
  SELECT
      s.id,
      s.firstname,
      s.lastname,
      s.secondname,
      s.birthdate,
      s.birthplace,
      s.pesel,
      s.addressstreet,
      s.addresscity,
      s.addresszip,
      s.telephoneno,
      c.id AS company_id,
      c.name AS company_name
  FROM inserted s
  LEFT JOIN companies c ON c.id = s.company_id
`

type CreateStudentParams struct {
	Firstname     string      `json:"firstname"`
	Lastname      string      `json:"lastname"`
	Secondname    pgtype.Text `json:"secondname"`
	Birthdate     pgtype.Date `json:"birthdate"`
	Birthplace    string      `json:"birthplace"`
	Pesel         pgtype.Text `json:"pesel"`
	Addressstreet pgtype.Text `json:"addressstreet"`
	Addresscity   pgtype.Text `json:"addresscity"`
	Addresszip    pgtype.Text `json:"addresszip"`
	Telephoneno   pgtype.Text `json:"telephoneno"`
	CompanyID     pgtype.Int8 `json:"company_id"`
}

type CreateStudentRow struct {
	ID            int64       `json:"id"`
	Firstname     string      `json:"firstname"`
	Lastname      string      `json:"lastname"`
	Secondname    pgtype.Text `json:"secondname"`
	Birthdate     pgtype.Date `json:"birthdate"`
	Birthplace    string      `json:"birthplace"`
	Pesel         pgtype.Text `json:"pesel"`
	Addressstreet pgtype.Text `json:"addressstreet"`
	Addresscity   pgtype.Text `json:"addresscity"`
	Addresszip    pgtype.Text `json:"addresszip"`
	Telephoneno   pgtype.Text `json:"telephoneno"`
	CompanyID     pgtype.Int8 `json:"company_id"`
	CompanyName   pgtype.Text `json:"company_name"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (CreateStudentRow, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.Firstname,
		arg.Lastname,
		arg.Secondname,
		arg.Birthdate,
		arg.Birthplace,
		arg.Pesel,
		arg.Addressstreet,
		arg.Addresscity,
		arg.Addresszip,
		arg.Telephoneno,
		arg.CompanyID,
	)
	var i CreateStudentRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Secondname,
		&i.Birthdate,
		&i.Birthplace,
		&i.Pesel,
		&i.Addressstreet,
		&i.Addresscity,
		&i.Addresszip,
		&i.Telephoneno,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
  SELECT
      s.id,
      s.firstname,
      s.lastname,
      s.secondname,
      s.birthdate,
      s.birthplace,
      s.pesel,
      s.addressstreet,
      s.addresscity,
      s.addresszip,
      s.telephoneno,
      c.id AS company_id,
      c.name AS company_name
  FROM students s
  LEFT JOIN companies c ON c.id = s.company_id
  WHERE s.id = $1
`

type GetStudentByIDRow struct {
	ID            int64       `json:"id"`
	Firstname     string      `json:"firstname"`
	Lastname      string      `json:"lastname"`
	Secondname    pgtype.Text `json:"secondname"`
	Birthdate     pgtype.Date `json:"birthdate"`
	Birthplace    string      `json:"birthplace"`
	Pesel         pgtype.Text `json:"pesel"`
	Addressstreet pgtype.Text `json:"addressstreet"`
	Addresscity   pgtype.Text `json:"addresscity"`
	Addresszip    pgtype.Text `json:"addresszip"`
	Telephoneno   pgtype.Text `json:"telephoneno"`
	CompanyID     pgtype.Int8 `json:"company_id"`
	CompanyName   pgtype.Text `json:"company_name"`
}

func (q *Queries) GetStudentByID(ctx context.Context, id int64) (GetStudentByIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i GetStudentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Secondname,
		&i.Birthdate,
		&i.Birthplace,
		&i.Pesel,
		&i.Addressstreet,
		&i.Addresscity,
		&i.Addresszip,
		&i.Telephoneno,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
  SELECT
      s.id,
      s.firstname,
      s.lastname,
      s.secondname,
      s.birthdate,
      s.birthplace,
      s.pesel,
      c.id AS company_id,
      c.name AS company_name
  FROM students s
  LEFT JOIN companies c ON c.id = s.company_id
  WHERE
      (
          $1::text IS NULL
          OR NOT EXISTS (
              SELECT 1
              FROM unnest(
                  regexp_split_to_array(
                      trim(regexp_replace($1::text, '[,\s]+', ' ', 'g')),
                      ' '
                  )
              ) AS term
              WHERE term <> ''
                AND COALESCE(s.firstname, '') NOT ILIKE '%' || term || '%'
                AND COALESCE(s.lastname, '') NOT ILIKE '%' || term || '%'
                AND COALESCE(s.pesel, '') NOT ILIKE '%' || term || '%'
          )
      )
      AND (
          $2::bigint IS NULL
          OR s.company_id = $2::bigint
      )
  ORDER BY s.lastname, s.firstname
  LIMIT $3
`

type ListStudentsParams struct {
	Search     pgtype.Text `json:"search"`
	CompanyID  pgtype.Int8 `json:"company_id"`
	LimitCount int32       `json:"limit_count"`
}

type ListStudentsRow struct {
	ID          int64       `json:"id"`
	Firstname   string      `json:"firstname"`
	Lastname    string      `json:"lastname"`
	Secondname  pgtype.Text `json:"secondname"`
	Birthdate   pgtype.Date `json:"birthdate"`
	Birthplace  string      `json:"birthplace"`
	Pesel       pgtype.Text `json:"pesel"`
	CompanyID   pgtype.Int8 `json:"company_id"`
	CompanyName pgtype.Text `json:"company_name"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents, arg.Search, arg.CompanyID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsRow{}
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Secondname,
			&i.Birthdate,
			&i.Birthplace,
			&i.Pesel,
			&i.CompanyID,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByCompanyID = `-- name: ListStudentsByCompanyID :many
  SELECT
      s.id,
      s.firstname,
      s.lastname,
      s.secondname,
      s.birthdate,
      s.birthplace,
      s.pesel
  FROM students s
  WHERE s.company_id = $1
  ORDER BY s.lastname, s.firstname
`

type ListStudentsByCompanyIDRow struct {
	ID         int64       `json:"id"`
	Firstname  string      `json:"firstname"`
	Lastname   string      `json:"lastname"`
	Secondname pgtype.Text `json:"secondname"`
	Birthdate  pgtype.Date `json:"birthdate"`
	Birthplace string      `json:"birthplace"`
	Pesel      pgtype.Text `json:"pesel"`
}

func (q *Queries) ListStudentsByCompanyID(ctx context.Context, companyID pgtype.Int8) ([]ListStudentsByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByCompanyID, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByCompanyIDRow{}
	for rows.Next() {
		var i ListStudentsByCompanyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Firstname,
			&i.Lastname,
			&i.Secondname,
			&i.Birthdate,
			&i.Birthplace,
			&i.Pesel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
  WITH updated AS (
      UPDATE students AS s
      SET
          firstname = $1,
          lastname = $2,
          secondname = $3,
          birthdate = $4,
          birthplace = $5,
          pesel = $6,
          addressstreet = $7,
          addresscity = $8,
          addresszip = $9,
          telephoneno = $10,
          company_id = $11
      WHERE s.id = $12
       RETURNING
          s.id,
          s.firstname,
          s.lastname,
          s.secondname,
          s.birthdate,
          s.birthplace,
          s.pesel,
          s.addressstreet,
          s.addresscity,
          s.addresszip,
          s.telephoneno,
          s.company_id

  )
  SELECT
      u.id,
      u.firstname,
      u.lastname,
      u.secondname,
      u.birthdate,
      u.birthplace,
      u.pesel,
      u.addressstreet,
      u.addresscity,
      u.addresszip,
      u.telephoneno,
      c.id AS company_id,
      c.name AS company_name
  FROM updated u
  LEFT JOIN companies c ON c.id = u.company_id
`

type UpdateStudentParams struct {
	Firstname     string      `json:"firstname"`
	Lastname      string      `json:"lastname"`
	Secondname    pgtype.Text `json:"secondname"`
	Birthdate     pgtype.Date `json:"birthdate"`
	Birthplace    string      `json:"birthplace"`
	Pesel         pgtype.Text `json:"pesel"`
	Addressstreet pgtype.Text `json:"addressstreet"`
	Addresscity   pgtype.Text `json:"addresscity"`
	Addresszip    pgtype.Text `json:"addresszip"`
	Telephoneno   pgtype.Text `json:"telephoneno"`
	CompanyID     pgtype.Int8 `json:"company_id"`
	StudentID     int64       `json:"student_id"`
}

type UpdateStudentRow struct {
	ID            int64       `json:"id"`
	Firstname     string      `json:"firstname"`
	Lastname      string      `json:"lastname"`
	Secondname    pgtype.Text `json:"secondname"`
	Birthdate     pgtype.Date `json:"birthdate"`
	Birthplace    string      `json:"birthplace"`
	Pesel         pgtype.Text `json:"pesel"`
	Addressstreet pgtype.Text `json:"addressstreet"`
	Addresscity   pgtype.Text `json:"addresscity"`
	Addresszip    pgtype.Text `json:"addresszip"`
	Telephoneno   pgtype.Text `json:"telephoneno"`
	CompanyID     pgtype.Int8 `json:"company_id"`
	CompanyName   pgtype.Text `json:"company_name"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (UpdateStudentRow, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.Firstname,
		arg.Lastname,
		arg.Secondname,
		arg.Birthdate,
		arg.Birthplace,
		arg.Pesel,
		arg.Addressstreet,
		arg.Addresscity,
		arg.Addresszip,
		arg.Telephoneno,
		arg.CompanyID,
		arg.StudentID,
	)
	var i UpdateStudentRow
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Secondname,
		&i.Birthdate,
		&i.Birthplace,
		&i.Pesel,
		&i.Addressstreet,
		&i.Addresscity,
		&i.Addresszip,
		&i.Telephoneno,
		&i.CompanyID,
		&i.CompanyName,
	)
	return i, err
}
