// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const countAdminUsers = `-- name: CountAdminUsers :one
  SELECT COUNT(*)
  FROM users
  WHERE role = $1
`

func (q *Queries) CountAdminUsers(ctx context.Context, role int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
  INSERT INTO users (
      email,
      password,
      firstname,
      lastname,
      role
  ) VALUES (
      $1, $2, $3, $4, $5
  )
  RETURNING
      id,
      email,
      firstname,
      lastname,
      role
`

type CreateUserParams struct {
	Email     string `json:"email"`
	Password  []byte `json:"password"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Role      int32  `json:"role"`
}

type CreateUserRow struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Role      int32  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.Firstname,
		arg.Lastname,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
  DELETE FROM users
  WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUsers = `-- name: ListUsers :many
  SELECT
      id,
      email,
      firstname,
      lastname,
      role
  FROM users
  ORDER BY lastname, firstname, email
`

type ListUsersRow struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Role      int32  `json:"role"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Firstname,
			&i.Lastname,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
  UPDATE users
  SET
      email = $2,
      firstname = $3,
      lastname = $4,
      role = $5
  WHERE id = $1
  RETURNING
      id,
      email,
      firstname,
      lastname,
      role
`

type UpdateUserParams struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Role      int32  `json:"role"`
}

type UpdateUserRow struct {
	ID        int64  `json:"id"`
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Role      int32  `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Role,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
  UPDATE users
  SET password = $2
  WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password []byte `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}
