// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireWebhookSubjectLock = `-- name: AcquireWebhookSubjectLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('webhook:' || $1::text, 0))
`

// Szereguje zapis zdarzeń jednego przedmiotu (zaświadczenia, kursu) do końca transakcji,
// dzięki czemu znaczniki czasu rosną w kolejności zatwierdzania.
func (q *Queries) AcquireWebhookSubjectLock(ctx context.Context, subjectKey string) error {
	_, err := q.db.Exec(ctx, acquireWebhookSubjectLock, subjectKey)
	return err
}

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
WITH due AS (
    SELECT d.id
    FROM webhook_deliveries d
    WHERE d.status = 'pending'
      AND d.next_attempt_at <= now()
      AND (d.locked_until IS NULL OR d.locked_until < now())
      AND NOT EXISTS (
          SELECT 1
          FROM webhook_deliveries older
          WHERE older.endpoint_id = d.endpoint_id
            AND older.subject_key = d.subject_key
            AND older.status = 'pending'
            AND older.id < d.id
      )
    ORDER BY d.next_attempt_at, d.id
    LIMIT $2
    FOR UPDATE OF d SKIP LOCKED
)
UPDATE webhook_deliveries d
SET locked_until = now() + make_interval(secs => $1::double precision),
    attempts = d.attempts + 1
FROM due, webhook_events ev, webhook_endpoints en
WHERE d.id = due.id
  AND ev.id = d.event_id
  AND en.id = d.endpoint_id
RETURNING d.id, d.attempts, ev.event_type, ev.payload, en.id AS endpoint_id, en.url, en.secret
`

type ClaimWebhookDeliveriesParams struct {
	LeaseSeconds float64 `json:"lease_seconds"`
	BatchSize    int32   `json:"batch_size"`
}

type ClaimWebhookDeliveriesRow struct {
	ID         int64  `json:"id"`
	Attempts   int32  `json:"attempts"`
	EventType  string `json:"event_type"`
	Payload    []byte `json:"payload"`
	EndpointID int64  `json:"endpoint_id"`
	Url        string `json:"url"`
	Secret     string `json:"secret"`
}

// Pobiera doręczenia gotowe do wysyłki i zakłada na nie dzierżawę. Doręczenie czeka, dopóki
// starsze doręczenie tego samego przedmiotu do tego samego odbiorcy jest w toku - odbiorca
// dostaje zdarzenia o dokumencie w kolejności ich powstania.
func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]ClaimWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimWebhookDeliveriesRow{}
	for rows.Next() {
		var i ClaimWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Attempts,
			&i.EventType,
			&i.Payload,
			&i.EndpointID,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
WITH ev AS (
    INSERT INTO webhook_events (event_type, subject_key, occurred_at, payload)
    VALUES ($1::text, $2::text, $3::timestamptz, $4::bytea)
    RETURNING id, subject_key
),
deliveries AS (
    INSERT INTO webhook_deliveries (event_id, endpoint_id, subject_key)
    SELECT ev.id, en.id, ev.subject_key
    FROM ev
    CROSS JOIN webhook_endpoints en
    WHERE en.active
    RETURNING id
)
SELECT (SELECT id FROM ev)::bigint AS event_id, (SELECT count(*) FROM deliveries)::bigint AS deliveries
`

type InsertWebhookEventParams struct {
	EventType  string             `json:"event_type"`
	SubjectKey string             `json:"subject_key"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Payload    []byte             `json:"payload"`
}

type InsertWebhookEventRow struct {
	EventID    int64 `json:"event_id"`
	Deliveries int64 `json:"deliveries"`
}

// Zapisuje zdarzenie i doręczenia do wszystkich aktywnych odbiorców.
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (InsertWebhookEventRow, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.EventType,
		arg.SubjectKey,
		arg.OccurredAt,
		arg.Payload,
	)
	var i InsertWebhookEventRow
	err := row.Scan(&i.EventID, &i.Deliveries)
	return i, err
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries
SET status = 'delivered',
    delivered_at = now(),
    locked_until = NULL,
    last_status_code = $1,
    last_error = NULL
WHERE id = $2
`

type MarkWebhookDeliveredParams struct {
	StatusCode pgtype.Int4 `json:"status_code"`
	ID         int64       `json:"id"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, arg.StatusCode, arg.ID)
	return err
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_deliveries
SET status = 'failed',
    locked_until = NULL,
    last_status_code = $1,
    last_error = $2
WHERE id = $3
`

type MarkWebhookFailedParams struct {
	StatusCode pgtype.Int4 `json:"status_code"`
	LastError  pgtype.Text `json:"last_error"`
	ID         int64       `json:"id"`
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.StatusCode, arg.LastError, arg.ID)
	return err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :exec
UPDATE webhook_deliveries
SET next_attempt_at = now() + make_interval(secs => $1::double precision),
    locked_until = NULL,
    last_status_code = $2,
    last_error = $3
WHERE id = $4
`

type MarkWebhookRetryParams struct {
	DelaySeconds float64     `json:"delay_seconds"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	LastError    pgtype.Text `json:"last_error"`
	ID           int64       `json:"id"`
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markWebhookRetry,
		arg.DelaySeconds,
		arg.StatusCode,
		arg.LastError,
		arg.ID,
	)
	return err
}

const nextWebhookEventTimestamp = `-- name: NextWebhookEventTimestamp :one
SELECT GREATEST(
    clock_timestamp(),
    COALESCE(
        (SELECT max(occurred_at) FROM webhook_events WHERE subject_key = $1::text),
        '-infinity'::timestamptz
    ) + interval '1 microsecond'
)::timestamptz AS occurred_at
`

// Bieżący czas, ale ściśle późniejszy od ostatniego zdarzenia tego samego przedmiotu.
func (q *Queries) NextWebhookEventTimestamp(ctx context.Context, subjectKey string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextWebhookEventTimestamp, subjectKey)
	var occurred_at pgtype.Timestamptz
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const notifyWebhookDispatcher = `-- name: NotifyWebhookDispatcher :exec
SELECT pg_notify('webhook_deliveries', '')
`

// NOTIFY w transakcji dociera do nasłuchujących dopiero po jej zatwierdzeniu.
func (q *Queries) NotifyWebhookDispatcher(ctx context.Context) error {
	_, err := q.db.Exec(ctx, notifyWebhookDispatcher)
	return err
}
