CREATE TABLE companies (
    id bigint PRIMARY KEY,
    name text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    zipcode text NOT NULL,
    nip text NOT NULL,
    email text,
    contactperson text,
    telephoneno text NOT NULL,
    note text,
    expiry_notifications_enabled boolean NOT NULL DEFAULT false,
    expiry_notification_email text,
    external_id text,
    CONSTRAINT companies_external_id_length CHECK (char_length(external_id) BETWEEN 1 AND 64)
);
CREATE UNIQUE INDEX check_unique_nip ON companies (nip);
CREATE UNIQUE INDEX companies_external_id_uidx ON companies (external_id) WHERE external_id IS NOT NULL;

CREATE TABLE students (
    id bigint PRIMARY KEY,
    firstname text NOT NULL,
    lastname text NOT NULL,
    secondname text,
    birthdate date NOT NULL,
    birthplace text NOT NULL,
    pesel text,
    addressstreet text,
    addresscity text,
    telephoneno text,
    company_id bigint,
    addresszip text,
    external_id text,
    CONSTRAINT students_external_id_length CHECK (char_length(external_id) BETWEEN 1 AND 64)
);

CREATE UNIQUE INDEX students_external_id_uidx ON students (external_id) WHERE external_id IS NOT NULL;

ALTER TABLE students
    ADD CONSTRAINT students_company_id_fkey
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;

CREATE INDEX students_company_id_idx
    ON students (company_id)
    WHERE company_id IS NOT NULL;

-- Unikalność osoby: dokładny zapis (0017) oraz bez rozróżniania wielkości liter
-- i spacji na brzegach (0018; na bazach z istniejącymi duplikatami do czasu ich
-- uporządkowania zamiast tego indeksu działa students_person_lookup_idx z 0017).
ALTER TABLE students
    ADD CONSTRAINT students_person_unique UNIQUE (firstname, lastname, birthdate);

CREATE UNIQUE INDEX students_person_normalized_uidx
    ON students (lower(btrim(firstname)), lower(btrim(lastname)), birthdate);

CREATE TABLE users (
    id bigint PRIMARY KEY,
    email text NOT NULL,
    password bytea NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    role integer NOT NULL,
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE api_sessions (
    token text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE courses (
    id bigint PRIMARY KEY,
    mainname text,
    name text NOT NULL,
    symbol text NOT NULL,
    expirytime text,
    courseprogram json,
    certfrontpage text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    delivered_by_platform boolean NOT NULL DEFAULT false
);

CREATE INDEX courses_updated_at_idx ON courses (updated_at);

CREATE TABLE course_certificate_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    language_code text NOT NULL,
    course_name text NOT NULL,
    course_program json NOT NULL,
    cert_front_page text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT course_certificate_translations_language_code_check
        CHECK (
            language_code = lower(btrim(language_code))
            AND language_code <> ''
            AND language_code <> 'pl'
        ),
    CONSTRAINT course_certificate_translations_course_language_unique
        UNIQUE (course_id, language_code)
);
CREATE INDEX course_certificate_translations_course_id_idx
    ON course_certificate_translations (course_id);


CREATE TABLE registries (
    id bigint PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    year bigint NOT NULL,
    number integer NOT NULL,
    CONSTRAINT registries_course_year_number_key UNIQUE (course_id, year, number)
);

CREATE TABLE certificates (
    id bigint NOT NULL PRIMARY KEY,
    date date NOT NULL,
    student_id integer NOT NULL REFERENCES students(id),
    coursedatestart date NOT NULL,
    coursedateend date,
    registry_id bigint NOT NULL REFERENCES registries(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    language_code text NOT NULL DEFAULT 'pl',
    student_firstname_snapshot text NOT NULL,
    student_secondname_snapshot text,
    student_lastname_snapshot text NOT NULL,
    student_birthdate_snapshot date NOT NULL,
    student_birthplace_snapshot text NOT NULL,
    student_pesel_snapshot text,
    company_name_snapshot text,
    course_name_snapshot text NOT NULL,
    course_symbol_snapshot text NOT NULL,
    course_expiry_time_snapshot text,
    course_program_snapshot json NOT NULL,
    cert_front_page_snapshot text NOT NULL,
    deleted_at timestamptz,
    deleted_by_user_id bigint REFERENCES users(id) ON DELETE RESTRICT,
    delete_reason text,
    company_id_snapshot bigint REFERENCES companies(id) ON DELETE RESTRICT,
    verification_code text NOT NULL,
    revoked_at timestamptz,
    revoke_reason text,
    revoked_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    supersedes_id bigint REFERENCES certificates(id) ON DELETE RESTRICT,
    duplicate_reason text,
    idempotency_key text,
    CONSTRAINT certificates_revoke_consistency CHECK (
        (revoked_at IS NULL AND revoke_reason IS NULL)
        OR (revoked_at IS NOT NULL AND revoke_reason IS NOT NULL AND btrim(revoke_reason) <> '')
    ),
    CONSTRAINT certificates_duplicate_consistency CHECK (
        (supersedes_id IS NULL AND duplicate_reason IS NULL)
        OR (supersedes_id IS NOT NULL AND duplicate_reason IS NOT NULL AND btrim(duplicate_reason) <> '')
    ),
    CONSTRAINT certificates_supersedes_not_self CHECK (supersedes_id <> id),
    CONSTRAINT certificates_language_code_check
        CHECK (
            language_code = lower(btrim(language_code))
            AND language_code <> ''
        ),
    CONSTRAINT certificates_verification_code_format
        CHECK (verification_code ~ '^[2-9A-HJ-NP-Z]{12}$')
);

-- Kod weryfikacyjny: losowy, unikalny, niezmienny (migracja 0021).
CREATE FUNCTION generate_certificate_verification_code() RETURNS text
    LANGUAGE plpgsql
    VOLATILE
AS $$
DECLARE
    alphabet constant text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
    positions constant int[] := ARRAY[0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14];
    random_bytes bytea;
    code text;
    pos int;
BEGIN
    LOOP
        random_bytes := uuid_send(gen_random_uuid());
        code := '';
        FOREACH pos IN ARRAY positions LOOP
            code := code || substr(alphabet, get_byte(random_bytes, pos) % 32 + 1, 1);
        END LOOP;
        EXIT WHEN NOT EXISTS (SELECT 1 FROM certificates WHERE verification_code = code);
    END LOOP;
    RETURN code;
END;
$$;

ALTER TABLE certificates
    ALTER COLUMN verification_code SET DEFAULT generate_certificate_verification_code();

CREATE UNIQUE INDEX certificates_verification_code_uidx ON certificates (verification_code);

CREATE UNIQUE INDEX certificates_supersedes_id_uidx ON certificates (supersedes_id) WHERE supersedes_id IS NOT NULL AND deleted_at IS NULL;

CREATE FUNCTION certificates_verification_code_immutable() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.verification_code IS DISTINCT FROM OLD.verification_code THEN
        RAISE EXCEPTION 'certificates.verification_code is immutable (certificate id %)', OLD.id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER certificates_verification_code_immutable
    BEFORE UPDATE OF verification_code ON certificates
    FOR EACH ROW
    EXECUTE FUNCTION certificates_verification_code_immutable();

CREATE INDEX certificates_company_id_snapshot_idx
    ON certificates (company_id_snapshot)
    WHERE company_id_snapshot IS NOT NULL;

CREATE UNIQUE INDEX certificates_active_registry_uidx
    ON certificates (registry_id)
    WHERE deleted_at IS NULL;

CREATE TABLE training_journals (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      course_id bigint NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
      company_id bigint REFERENCES companies(id) ON DELETE RESTRICT,
      title text NOT NULL,
      course_symbol text NOT NULL,
      organizer_name text NOT NULL,
      organizer_address text,
      location text NOT NULL,
      form_of_training text NOT NULL,
      legal_basis text NOT NULL,
      date_start date NOT NULL,
      date_end date NOT NULL,
      total_hours numeric(6,2) NOT NULL DEFAULT 0,
      notes text,
      status text NOT NULL DEFAULT 'draft',
      created_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      closed_at timestamptz,
      CONSTRAINT training_journals_status_check
          CHECK (status IN ('draft', 'closed')),
      CONSTRAINT training_journals_dates_check
          CHECK (date_end >= date_start),
      CONSTRAINT training_journals_total_hours_check
          CHECK (total_hours >= 0)
  );

  CREATE TABLE training_journal_attendees (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      student_id bigint NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
      certificate_id bigint REFERENCES certificates(id) ON DELETE SET NULL,
      full_name_snapshot text NOT NULL,
      birthdate_snapshot date,
      company_name_snapshot text,
      sort_order integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendees_sort_order_check
          CHECK (sort_order >= 0),
      CONSTRAINT training_journal_attendees_journal_student_unique
          UNIQUE (journal_id, student_id)
  );

  CREATE TABLE training_journal_sessions (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      session_date date NOT NULL,
      start_time time,
      end_time time,
      hours numeric(6,2) NOT NULL,
      topic text NOT NULL,
      trainer_name text NOT NULL,
      sort_order integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_sessions_hours_check
          CHECK (hours > 0),
      CONSTRAINT training_journal_sessions_sort_order_check
          CHECK (sort_order >= 0),
      CONSTRAINT training_journal_sessions_time_check
          CHECK (
              start_time IS NULL
              OR end_time IS NULL
              OR end_time >= start_time
          )
  );

  CREATE TABLE training_journal_attendance (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_session_id bigint NOT NULL REFERENCES training_journal_sessions(id) ON DELETE CASCADE,
      journal_attendee_id bigint NOT NULL REFERENCES training_journal_attendees(id) ON DELETE CASCADE,
      present boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendance_session_attendee_unique
          UNIQUE (journal_session_id, journal_attendee_id)
  );

  CREATE INDEX training_journals_course_id_idx
      ON training_journals (course_id);

  CREATE INDEX training_journals_company_id_idx
      ON training_journals (company_id);

  CREATE INDEX training_journals_status_date_start_idx
      ON training_journals (status, date_start DESC);

  CREATE INDEX training_journal_attendees_journal_id_sort_order_idx
      ON training_journal_attendees (journal_id, sort_order, id);

  CREATE UNIQUE INDEX training_journal_attendees_certificate_id_uidx
      ON training_journal_attendees (certificate_id)
      WHERE certificate_id IS NOT NULL;

  CREATE INDEX training_journal_sessions_journal_id_session_date_sort_order_idx
      ON training_journal_sessions (journal_id, session_date, sort_order, id);

  CREATE INDEX training_journal_attendance_session_id_idx
      ON training_journal_attendance (journal_session_id);

  CREATE INDEX training_journal_attendance_attendee_id_idx
      ON training_journal_attendance (journal_attendee_id);


  CREATE TABLE training_journal_attendance_scans (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      file_name text NOT NULL,
      content_type text NOT NULL,
      file_size bigint NOT NULL,
      file_data bytea NOT NULL,
      uploaded_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendance_scans_file_size_check CHECK (file_size > 0),
      CONSTRAINT training_journal_attendance_scans_journal_unique UNIQUE (journal_id)
  );

  CREATE INDEX training_journal_attendance_scans_uploaded_by_idx
      ON training_journal_attendance_scans (uploaded_by_user_id);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL,
    entity_id bigint NOT NULL,
    action text NOT NULL,
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    actor_user_email_snapshot text,
    actor_user_name_snapshot text,
    request_id text,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_entity_created_idx
    ON audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_log_actor_created_idx
    ON audit_log (actor_user_id, created_at DESC);
CREATE INDEX audit_log_created_idx
    ON audit_log (created_at DESC);

CREATE TABLE training_journal_signed_scans(
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      file_name text NOT NULL,
      content_type text NOT NULL,
      file_size bigint NOT NULL,
      file_data bytea NOT NULL,
      uploaded_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_signed_scans_file_size_check CHECK (file_size > 0),
      CONSTRAINT training_journal_signed_scans_journal_unique UNIQUE (journal_id)
  );

CREATE INDEX training_journal_signed_scans_uploaded_by_idx
      ON training_journal_signed_scans(uploaded_by_user_id);

CREATE TABLE api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    prefix text NOT NULL,
    token_hash text NOT NULL UNIQUE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scopes text[] NOT NULL DEFAULT '{}',
    expires_at timestamptz,
    last_used_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT api_keys_name_not_blank CHECK (btrim(name) <> '')
);

CREATE INDEX api_keys_user_id_idx ON api_keys (user_id);

CREATE INDEX api_keys_active_created_idx
    ON api_keys (created_at DESC)
    WHERE revoked_at IS NULL;

CREATE TABLE idempotency_keys (
    key text PRIMARY KEY,
    request_hash text NOT NULL,
    certificate_id bigint NOT NULL REFERENCES certificates(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT idempotency_keys_key_length CHECK (char_length(key) BETWEEN 1 AND 255)
);

CREATE INDEX idempotency_keys_created_at_idx ON idempotency_keys (created_at);

CREATE FUNCTION courses_touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF (to_jsonb(NEW) - 'updated_at') IS DISTINCT FROM (to_jsonb(OLD) - 'updated_at') THEN
        NEW.updated_at := clock_timestamp();
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER courses_touch_updated_at
    BEFORE UPDATE ON courses
    FOR EACH ROW
    EXECUTE FUNCTION courses_touch_updated_at();

CREATE FUNCTION course_translations_touch_course() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
        AND (to_jsonb(NEW) - 'updated_at' - 'created_at') IS NOT DISTINCT FROM (to_jsonb(OLD) - 'updated_at' - 'created_at') THEN
        RETURN NULL;
    END IF;

    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        UPDATE courses SET updated_at = clock_timestamp() WHERE id = OLD.course_id;
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') AND (TG_OP = 'INSERT' OR NEW.course_id <> OLD.course_id) THEN
        UPDATE courses SET updated_at = clock_timestamp() WHERE id = NEW.course_id;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER course_translations_touch_course
    AFTER INSERT OR UPDATE OR DELETE ON course_certificate_translations
    FOR EACH ROW
    EXECUTE FUNCTION course_translations_touch_course();

CREATE TABLE webhook_endpoints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text NOT NULL,
    secret text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_endpoints_url_http CHECK (url ~ '^https?://'),
    CONSTRAINT webhook_endpoints_secret_not_blank CHECK (btrim(secret) <> '')
);

CREATE TABLE webhook_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    subject_key text NOT NULL,
    occurred_at timestamptz NOT NULL,
    payload bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX webhook_events_subject_idx ON webhook_events (subject_key, occurred_at DESC);

CREATE TABLE webhook_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES webhook_events(id) ON DELETE CASCADE,
    endpoint_id bigint NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE,
    subject_key text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    locked_until timestamptz,
    last_status_code integer,
    last_error text,
    delivered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT webhook_deliveries_status_check CHECK (status IN ('pending', 'delivered', 'failed')),
    CONSTRAINT webhook_deliveries_event_endpoint_unique UNIQUE (event_id, endpoint_id)
);

-- Wybór kolejnych doręczeń do wysłania.
CREATE INDEX webhook_deliveries_pending_idx
    ON webhook_deliveries (next_attempt_at, id)
    WHERE status = 'pending';

-- Kolejność per odbiorca i przedmiot: starsze oczekujące doręczenie blokuje nowsze.
CREATE INDEX webhook_deliveries_subject_pending_idx
    ON webhook_deliveries (endpoint_id, subject_key, id)
    WHERE status = 'pending';
