CREATE TABLE companies (
    id bigint PRIMARY KEY,
    name text NOT NULL,
    street text NOT NULL,
    city text NOT NULL,
    zipcode text NOT NULL,
    nip text NOT NULL,
    email text,
    contactperson text,
    telephoneno text NOT NULL,
    note text
);
CREATE UNIQUE INDEX check_unique_nip ON companies (nip);

CREATE TABLE students (
    id bigint PRIMARY KEY,
    firstname text NOT NULL,
    lastname text NOT NULL,
    secondname text,
    birthdate date NOT NULL,
    birthplace text NOT NULL,
    pesel text,
    addressstreet text,
    addresscity text,
    telephoneno text,
    company_id bigint,
    addresszip text
);

CREATE TABLE users (
    id bigint PRIMARY KEY,
    email text NOT NULL,
    password bytea NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    role integer NOT NULL
);

CREATE TABLE api_sessions (
    token text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE courses (
    id bigint PRIMARY KEY,
    mainname text,
    name text NOT NULL,
    symbol text NOT NULL,
    expirytime text,
    courseprogram json,
    certfrontpage text
);

CREATE TABLE course_certificate_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    language_code text NOT NULL,
    course_name text NOT NULL,
    course_program json NOT NULL,
    cert_front_page text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT course_certificate_translations_language_code_check
        CHECK (
            language_code = lower(btrim(language_code))
            AND language_code <> ''
            AND language_code <> 'pl'
        ),
    CONSTRAINT course_certificate_translations_course_language_unique
        UNIQUE (course_id, language_code)
);
CREATE INDEX course_certificate_translations_course_id_idx
    ON course_certificate_translations (course_id);


CREATE TABLE registries (
    id bigint PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    year bigint NOT NULL,
    number integer NOT NULL
);

CREATE TABLE certificates (
    id bigint NOT NULL PRIMARY KEY,
    date date NOT NULL,
    student_id integer NOT NULL REFERENCES students(id),
    coursedatestart date NOT NULL,
    coursedateend date,
    registry_id bigint NOT NULL REFERENCES registries(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    language_code text NOT NULL DEFAULT 'pl',
    student_firstname_snapshot text NOT NULL,
    student_secondname_snapshot text,
    student_lastname_snapshot text NOT NULL,
    student_birthdate_snapshot date NOT NULL,
    student_birthplace_snapshot text NOT NULL,
    student_pesel_snapshot text,
    company_name_snapshot text,
    course_name_snapshot text NOT NULL,
    course_symbol_snapshot text NOT NULL,
    course_expiry_time_snapshot text,
    course_program_snapshot json NOT NULL,
    cert_front_page_snapshot text NOT NULL,
    deleted_at timestamptz,
    deleted_by_user_id bigint REFERENCES users(id) ON DELETE RESTRICT,
    delete_reason text,
    CONSTRAINT certificates_language_code_check
        CHECK (
            language_code = lower(btrim(language_code))
            AND language_code <> ''
        )
);

CREATE TABLE training_journals (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      course_id bigint NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
      company_id bigint REFERENCES companies(id) ON DELETE RESTRICT,
      title text NOT NULL,
      course_symbol text NOT NULL,
      organizer_name text NOT NULL,
      organizer_address text,
      location text NOT NULL,
      form_of_training text NOT NULL,
      legal_basis text NOT NULL,
      date_start date NOT NULL,
      date_end date NOT NULL,
      total_hours numeric(6,2) NOT NULL DEFAULT 0,
      notes text,
      status text NOT NULL DEFAULT 'draft',
      created_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      closed_at timestamptz,
      CONSTRAINT training_journals_status_check
          CHECK (status IN ('draft', 'closed')),
      CONSTRAINT training_journals_dates_check
          CHECK (date_end >= date_start),
      CONSTRAINT training_journals_total_hours_check
          CHECK (total_hours >= 0)
  );

  CREATE TABLE training_journal_attendees (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      student_id bigint NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
      certificate_id bigint REFERENCES certificates(id) ON DELETE SET NULL,
      full_name_snapshot text NOT NULL,
      birthdate_snapshot date,
      company_name_snapshot text,
      sort_order integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendees_sort_order_check
          CHECK (sort_order >= 0),
      CONSTRAINT training_journal_attendees_journal_student_unique
          UNIQUE (journal_id, student_id)
  );

  CREATE TABLE training_journal_sessions (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      session_date date NOT NULL,
      start_time time,
      end_time time,
      hours numeric(6,2) NOT NULL,
      topic text NOT NULL,
      trainer_name text NOT NULL,
      sort_order integer NOT NULL DEFAULT 0,
      created_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_sessions_hours_check
          CHECK (hours > 0),
      CONSTRAINT training_journal_sessions_sort_order_check
          CHECK (sort_order >= 0),
      CONSTRAINT training_journal_sessions_time_check
          CHECK (
              start_time IS NULL
              OR end_time IS NULL
              OR end_time >= start_time
          )
  );

  CREATE TABLE training_journal_attendance (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_session_id bigint NOT NULL REFERENCES training_journal_sessions(id) ON DELETE CASCADE,
      journal_attendee_id bigint NOT NULL REFERENCES training_journal_attendees(id) ON DELETE CASCADE,
      present boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendance_session_attendee_unique
          UNIQUE (journal_session_id, journal_attendee_id)
  );

  CREATE INDEX training_journals_course_id_idx
      ON training_journals (course_id);

  CREATE INDEX training_journals_company_id_idx
      ON training_journals (company_id);

  CREATE INDEX training_journals_status_date_start_idx
      ON training_journals (status, date_start DESC);

  CREATE INDEX training_journal_attendees_journal_id_sort_order_idx
      ON training_journal_attendees (journal_id, sort_order, id);

  CREATE UNIQUE INDEX training_journal_attendees_certificate_id_uidx
      ON training_journal_attendees (certificate_id)
      WHERE certificate_id IS NOT NULL;

  CREATE INDEX training_journal_sessions_journal_id_session_date_sort_order_idx
      ON training_journal_sessions (journal_id, session_date, sort_order, id);

  CREATE INDEX training_journal_attendance_session_id_idx
      ON training_journal_attendance (journal_session_id);

  CREATE INDEX training_journal_attendance_attendee_id_idx
      ON training_journal_attendance (journal_attendee_id);


  CREATE TABLE training_journal_attendance_scans (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      file_name text NOT NULL,
      content_type text NOT NULL,
      file_size bigint NOT NULL,
      file_data bytea NOT NULL,
      uploaded_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_attendance_scans_file_size_check CHECK (file_size > 0),
      CONSTRAINT training_journal_attendance_scans_journal_unique UNIQUE (journal_id)
  );

  CREATE INDEX training_journal_attendance_scans_uploaded_by_idx
      ON training_journal_attendance_scans (uploaded_by_user_id);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL,
    entity_id bigint NOT NULL,
    action text NOT NULL,
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    actor_user_email_snapshot text,
    actor_user_name_snapshot text,
    request_id text,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_entity_created_idx
    ON audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_log_actor_created_idx
    ON audit_log (actor_user_id, created_at DESC);
CREATE INDEX audit_log_created_idx
    ON audit_log (created_at DESC);

CREATE TABLE training_journal_signed_scans(
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journal_id bigint NOT NULL REFERENCES training_journals(id) ON DELETE CASCADE,
      file_name text NOT NULL,
      content_type text NOT NULL,
      file_size bigint NOT NULL,
      file_data bytea NOT NULL,
      uploaded_by_user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT training_journal_signed_scans_file_size_check CHECK (file_size > 0),
      CONSTRAINT training_journal_signed_scans_journal_unique UNIQUE (journal_id)
  );

CREATE INDEX training_journal_signed_scans_uploaded_by_idx
      ON training_journal_signed_scans(uploaded_by_user_id);
